rayon-rs/rayon

- README.md
- src/par_iter/collect.rs
- src/par_iter/map.rs
- src/par_iter/mod.rs
- src/par_iter/reduce.rs
- src/par_iter/slice.rs
- src/par_iter/test.rs
- src/par_iter/weight.rs
This adds a method `weight` that can be used to specify the relative weight of an operation. 1.0 means "very cheap". As expressed in the thread on #7, I would like to find a more elegant solution to this problem, but this seems like a simple thing to add for now.
Fixes #7.
> add a `weight` combinator

- src/par_iter/enumerate.rs
- src/par_iter/mod.rs
- src/par_iter/test.rs
Returns the index into the original sequence along with each item.
Works like `Iterator::enumerate()`, but of course with threaded jobs it
won't be visited in any guaranteed order.  It has to assume that the
size of each split is known exactly though, so this wouldn't work after
a filtering function, for instance.
> Add an `enumerate` combinator

- README.md
- src/par_iter/collect.rs
- src/par_iter/enumerate.rs
- src/par_iter/for_each.rs
- src/par_iter/len.rs
- src/par_iter/map.rs
- src/par_iter/mod.rs
- src/par_iter/reduce.rs
- src/par_iter/slice.rs
- src/par_iter/slice_mut.rs
- src/par_iter/state.rs
- src/par_iter/test.rs
- src/par_iter/weight.rs
- src/par_iter/zip.rs
This branch rearranges the `par_iter` module somewhat and closes various relatively simple issues. In terms of how `par_iter` is used, it adds various traits, and the new recommend pattern is as follows:
```rust
use rayon::par_iter::*; // get all the relevant traits
```
and then you can write `vec.par_iter()` and `vec.par_iter_mut()` and that sort of thing as normal. Note that calling `into_par_iter` directly is not recommended, as I plan to implement it for `Vec<T>` eventually, which would cause your code to start moving out of the vector rather than iterating over references.
Other changes:
- add `for_each`
- change how `ParallelIteratorState` works to be external-iterator-like
- add `zip`
- add `weight_max` convenience function
cc @polyfractal @eddyb @bjz @kaksmet
> Par iter and par iter mut

- src/par_iter/mod.rs
- src/par_iter/range.rs
- src/par_iter/test.rs
A par_iter/range.rs was already started, but not actually pulled in.
Range<T> is annoying to deal with generically, since its Iterator
depends on unstable Step, and its ExactSizeIterator is only for select
integral types (all but i64/u64).
Use a macro to implement just those Range<T> with ExactSizeIterator.
> impl ParallelIterator for Range<T> (for some T)

- neg-tests/cannot_collect_filtermap_data.rs
- neg-tests/cannot_zip_filtered_data.rs
- src/par_iter/collect.rs
- src/par_iter/enumerate.rs
- src/par_iter/filter.rs
- src/par_iter/filter_map.rs
- src/par_iter/map.rs
- src/par_iter/mod.rs
- src/par_iter/range.rs
- src/par_iter/slice.rs
- src/par_iter/slice_mut.rs
- src/par_iter/test.rs
- src/par_iter/weight.rs
- src/par_iter/zip.rs
@bjz here is an implementation of filter that I believe to be correct. I also refined the `ParallelIterator` hierarchy and fixed a few minor things.
I think a good next step would be to add `flat_map`, but also to generalize `collect` so that it works for collections of arbitrary types. In particular, one could add a rope-like version of vector that DOES work for filtered (or flat-mapped) iterators.
Note that this builds on https://github.com/nikomatsakis/rayon/pull/23.
> Implement filter and add notion of sparse iterators

- src/par_iter/README.md
- src/par_iter/collect.rs
- src/par_iter/enumerate.rs
- src/par_iter/filter.rs
- src/par_iter/filter_map.rs
- src/par_iter/flat_map.rs
- src/par_iter/for_each.rs
- src/par_iter/internal.rs
- src/par_iter/len.rs
- src/par_iter/map.rs
- src/par_iter/mod.rs
- src/par_iter/range.rs
- src/par_iter/reduce.rs
- src/par_iter/slice.rs
- src/par_iter/slice_mut.rs
- src/par_iter/state.rs
- src/par_iter/test.rs
- src/par_iter/util.rs
- src/par_iter/weight.rs
- src/par_iter/zip.rs
This commit history is kind of rambly but I don't have time to clean it up. The big bit of work here is support for flat-map, which required a lot of redesign. See the `par_iter/README.md` file for an overview. 
I think there is still tweaking to be done on these traits. For example, I'd like to reduce the unsafety, and maybe add some lifetimes to allow passing references for the shared state in the producer. But this will do for now.
cc @cuviper @bjz
> Implement a new parallel iterator scheme that supports flat-map

- .travis.yml
- src/par_iter/slice.rs
Slice's IntoParallelIterator was missing a `T: 'data`, upsetting rust 1.6.
This also adds rust stable to the travis script.  We can't run tests on stable
since compiletest_rs requires nightly features, but we can at least build it.
> Keep rayon stable

- Cargo.toml
- benches/factorial.rs
- benches/fibonacci.rs
- benches/pythagoras.rs
See each commit message for benchmark results on my i7-2600 (4 core, 8 threads)
running on Linux, Fedora 23 x86_64.
These aren't terribly interesting computations, nor are they really good demos
of rayon, as a lot of the results don't show good parallelization.  But they do
hammer on rayon pretty hard, so I hope they're still useful for comparing the
effects of any proposed rayon changes.
> Add a few simple benchmarks

- src/par_iter/enumerate.rs
- src/par_iter/internal.rs
- src/par_iter/map.rs
- src/par_iter/mod.rs
- src/par_iter/range.rs
- src/par_iter/slice.rs
- src/par_iter/slice_mut.rs
- src/par_iter/test.rs
- src/par_iter/weight.rs
- src/par_iter/zip.rs
This change was a bit of a pain, but makes sense conceptually, and should enable "moving" iterators quite gracefully (e.g., `Vec::into_par_iter`). The idea is to change `fn into_producer(self)` to instead be:
```rust
fn with_producer<WP: ProducerContinuation<Self::Item>>(self, wp: WP) -> WP::Output;
```
where `ProducerContinuation` is basically a callback with a specific continuation:
```rust
pub trait ProducerContinuation<ITEM> {
type Output;
fn with_producer<'p, P>(self, producer: P, shared: &'p P::Shared) -> Self::Output
where P: Producer<'p, Item=ITEM>;
}
```
This would be a closure, except that closures can't be generic in the way that `with_producer` is monomorphic. That is, to use a closure, we'd have to specify a particular kind of producer, whereas with the trait, the producer …
> Restructure producer to use a callback.

- benches/factorial.rs
- benches/fibonacci.rs
- benches/pythagoras.rs
I wanted to benchmark the changes in #37, but the benchmarks were broken due to the latest changes to support a way to indicate a limit on the number of threads that rayon can use.
This adapts to the new changes.
> Adapt benchmarks to the changes in the initialize function

- src/par_iter/mod.rs
- src/par_iter/test.rs
- src/par_iter/vec.rs
This is modeled similarly to what &mut[] does, except that values are
moved out with ptr::read, and any remains are dropped.
Fixes #17.
> Add Vec::into_par_iter

- Cargo.toml
- demo/nbody/Cargo.toml
- demo/nbody/src/main.rs
- demo/nbody/src/nbody.rs
- demo/nbody/src/visualize.rs
- src/par_iter/fold.rs
- src/par_iter/mod.rs
- src/par_iter/reduce.rs
- src/par_iter/test.rs
This updates the nbody benchmark in two ways:
1. Adds a mode (par-reduce) that uses reduction internally. Right now this is kind of clumsily done, resulting in code duplication. This version runs more slowly than the original but exercises more of the parallel iterators API (and might provide a good target for optimization).
- That said, I'd like to work on it a bit more to use parallel iterators better and remove DRY before we go too crazy.
2. Updates the visualizer to let you press `P`, `R`, or `S` during execution.
3. Updates the CLI to just use `--mode` universally.
cc @bjz
> Add a reduce version of nbody benchmark, some new combinators

- src/par_iter/mod.rs
- src/par_iter/slice.rs
- src/par_iter/slice_mut.rs
- src/par_iter/test.rs
- src/prelude.rs
Added `fn par_chunks` and `fn par_chunks_mut` methods.
These for iteration over chunks of slice in parallel. (The particular use case I am thinking of are things like processing the rows of a matrix that uses a slice in row-major order for its representation.)
> Added `fn par_chunks` and `fn par_chunks_mut` methods.

- src/api.rs
- src/job.rs
- src/thread_pool.rs
The key part is the missing guard in `steal_until`, which was causing the crashes because unwinding would overwrite the job data.
Another issue was that some injected jobs could be left hanging after the thread pool was terminated. This is resolved by aborting all injected jobs on termination.
I also changed the code back to using a trait and just wrapped the mutable values in `UnsafeCell`.
Fixes #58
> Fixes for panic propagation

- README.md
The README.md in the section  about atomicity metions:
A Cell offers a mutable slot with just two methods, get and set. Cells can only be used for Copy types that are safe to memcpy around, such as i32, **f32,** or even something **bigger** like (usize, usize, **f32**).
it mentions the f32 primitive and something bigger than that but again mentioning f32.
i'm assuming the intent was to say f64, this micro pr fixes that.
Liam Clark
> small readme doc fix saying f32 twice instead of f32 and f64.

- Cargo.toml
I'm extremely new in this project, and just try to do 'cargo test', but I have got problem with it: crate "compiletest_rs" was not built with errors like "/compiletest_rs-0.0.11/src/procsrv.rs:16:5: 16:37 error: unresolved import `std::dynamic_lib::DynamicLibrary`. Could not find `dynamic_lib` in `std` ". I'm looking to the "compiletest_rs" repository and find in commit with "Cargo.toml", with a comment "Bump 0.1.1" about "3 days ago". Looks like "compiletest_rs" change version numbering.
> Update compiletest_rs dependencies

- src/job.rs
- src/lib.rs
Eventually this can be unconditionally enabled, once `catch_panic` is in stable Rust.
> Update panic propagation for latest nightly

- src/log.rs
Attribute: #[allow(dead_code)] in src/log.rs is unnecessary now and can be safely removed.
> remove unnecessary attribute: #[allow(dead_code)]

- README.md
I often come past here, and a quick link to the docs would be helpful!
> Add link to rustdoc in README

- neg-tests-compile/cell_par_iter.rs
- src/par_iter/mod.rs
A few of the mutators were accepting Fn without Sync, even though their
resulting objects required Sync to implement further ParallelIterator.
You'd still get an error in using it, but a bit removed from the actual
problem.  Requiring Sync right away puts an error message right on the
problematic closure, so it's clear what needs fixing.
> par_iter: require more Fn Sync

- LICENSE-APACHE
- LICENSE-MIT
Matches the cargo license description, and the rust-lang license scheme.
> Add MIT/Apache license files.

- src/par_iter/mod.rs
- src/par_iter/slice.rs
- src/par_iter/slice_mut.rs
The constraints on their `Iter` no longer require them to have simple
references.  Their `Item` now represents the complete type that is
produced, which could be something like `(&K, &mut V)` on a map, for
instance.
There are also now blanket implementations for types whose references
already implement `IntoParallelIterator`, which wasn't possible before.
[breaking-change] Implementers of these traits may have to adapt to the
changed constraints, and may be forced out by the blanket impl.  Users
of the traits may be affected by the changed `Item` semantics.
Closes #90.
> Relax IntoParallelRefIterator and IntoParallelRefMutIterator

- demo/mergesort/Cargo.toml
- demo/mergesort/src/main.rs
It's a lot more parallelizable than quicksort. The critical path is O(log^3 n) versus O(n).
> demo: add mergesort

- src/par_iter/chain.rs
- src/par_iter/collect/consumer.rs
- src/par_iter/collections.rs
- src/par_iter/mod.rs
- src/par_iter/test.rs
Two parallel iterators of the same type act as one big iterator.  All
common properties are maintained: bounded, exact, and indexed.
`VecDeque` gets to be the first user, replacing its temporary vectors
instead with a chain over its pair of slices.
> Implement a chain combinator

- .travis.yml
- rayon-demo/src/nbody/nbody.rs
- rayon-demo/src/pythagoras/mod.rs
- src/par_iter/chain.rs
- src/par_iter/enumerate.rs
- src/par_iter/filter.rs
- src/par_iter/filter_map.rs
- src/par_iter/flat_map.rs
- src/par_iter/internal.rs
- src/par_iter/map.rs
- src/par_iter/weight.rs
- src/par_iter/zip.rs
This introduces an adaptive algorithm for splitting par_iter jobs, used
only as a default case when no weights are specified.  Initially, it
will split into enough jobs to fill every thread.  Then whenever a job
is stolen, that job will again be split enough for every thread.
This is roughly based on @Amanieu's description in the users forum of
the algorithm used by Async++ and TBB.
> RFC: adaptive "thief splitting" algorithm for par_iter

- rayon-demo/src/mergesort/mod.rs
This is @edre's fix in https://github.com/nikomatsakis/rayon/issues/105
> mergesort is correct on duplicate values

- Cargo.toml
- RELEASES.md
Lots of exciting stuff here!
- Parallel iterators now offer an adaptive weight scheme,
which means that explicit weights should no longer
be necessary in most cases! Thanks @cuviper!
- We are considering removing weights or changing the weight mechanism
before 1.0. Examples of scenarios where you still need weights even
with this adaptive mechanism would be great. Join the discussion
at <https://github.com/nikomatsakis/rayon/issues/111>.
- New (unstable) scoped threads API, see `rayon::scope` for details.
- You will need to supply the [cargo feature] `unstable`.
- The various demos and benchmarks have been consolidated into one
program, `rayon-demo`.
- Optimizations in Rayon's inner workings. Thanks @emilio!
- Update `num_cpus` to 1.0. Thanks @jamwt!
- Various internal cleanup in the …
> Release v0.4.3

- neg-tests-compile/scope_join_bad.rs
- pos-tests-run/scope_join.rs
- src/job.rs
- src/lib.rs
- src/scope/mod.rs
- src/scope/test.rs
- src/thread_pool.rs
This branch causes us to shift to a worker thread as soon as you call `scope()`; individual calls to `scope.spawn()` are thus forced to execute in a worker thread, I believe. Since the scope is executing in a worker thread, we can then change to use a `SpinLatch` for when the workers are done, and then use `steal_until()` to steal until that completes.
I'm quite happy with these changes, but unhappy with not having tests. We need some bigger scope benchmarks. Something modeled on servo would be ideal (i.e., descending a tree, doing work (and maybe creating scopes too?) at each step).
Fixes #108
cc @emilio
> Steal while scope blocks

- src/par_iter/internal.rs
Not sure if this is explicitly a rust `1.9.0` thing or not
> fix(thread_local): Removes unnecessary semicolon

- RELEASES.md
- rayon-demo/src/nbody/nbody.rs
- src/par_iter/fold.rs
- src/par_iter/mod.rs
- src/par_iter/reduce.rs
- src/par_iter/test.rs
We currently have too many variants of `reduce`. This brings us down to two:
- `reduce(identity, combine)`, which will combine elements in your iterator by calling `combine(l, r)`, and using `identity()` to produce an identity value when it needs to
- by taking a closure, we can remove the `Clone` bound on `reduce`
- by taking an identity, we can make the return value `T` and be maximally efficient
- `reduce_with(combine)`, which will combine elements in your iterator by calling `combine(l, r)`
- it does not take an identity, so it returns `None` if your iterator is empty
I've also stabilized and modified `fold` -- it might make sense to give it another name, though, like `partial_fold`. The new `fold` is kind of like sequential fold except that it operates only on subsequences …
> [RFC] [breaking-change] Simplify `reduce` and `fold`

- Cargo.toml
- RELEASES.md
- **Breaking change:** The `reduce` method has been vastly
simplified, and `reduce_with_identity` has been deprecated.
- **Breaking change:** The `fold` method has been changed. It used to
always reduce the values, but now instead it is a combinator that
returns a parallel iterator which can itself be reduced. See the
docs for more information.
- The following parallel iterator combinators are now available (thanks @cuviper!):
- `find_any()`: similar to `find` on a sequential iterator,
but doesn't necessarily return the *first* matching item
- `position_any()`: similar to `position` on a sequential iterator,
but doesn't necessarily return the index of *first* matching item
- `any()`, `all()`: just like their sequential counterparts
- The `count()` combinator is now available for parallel …
> Release Rayon 0.5.0

- rayon-demo/src/main.rs
- rayon-demo/src/map_collect.rs
- src/par_iter/collect/mod.rs
- src/par_iter/from_par_iter.rs
- src/par_iter/mod.rs
- src/par_iter/test.rs
- src/prelude.rs
Implement it for `Vec<T>` and `HashMap<K, V>`. The latter one is mildly
dubious, though I think it's functionality we will want to support (and
probably optimize over time). I included it in part to force type
inference hints.
cc #123
> add a `collect()` method to parallel iterators

- rayon-demo/src/map_collect.rs
- src/par_iter/from_par_iter.rs
- src/par_iter/test.rs
- Re-add the extra benchmarks from #135 
- Change the general collect to use `LinkedList<Vec<_>>`
- Add `BinaryHeap` and `VecDeque` for symmetry with `IntoParallelIterator` collections.
> Additions for parallel collect

- src/par_iter/internal.rs
It is not only unnecessary, it's misleading. The intution is that `move`
closures are needed to 'detach' the closure from the surrounding stack
frame, but of course we don't want to detach the closure from the
surrounding stack frame here.
> remove move keyword on closures from `bridge_producer_consumer`

- src/par_iter/internal.rs
- src/par_iter/range.rs
- src/par_iter/test.rs
These couldn't be exact iterators, because they could exceed a `usize`
length on 32-bit targets.  So this adds a `bridge_unindexed` helper
function to drive consumers directly with imprecise splits.  64-bit
ranges can use this while happily splitting in normal halves.
> Implement parallel Range<i64> and Range<u64>

- rayon-demo/src/main.rs
- rayon-demo/src/matmul/bench.rs
- rayon-demo/src/matmul/mod.rs
Includes both row-major order and Z order, demonstrating that
cache-obliviousness is more important than parallelism.
Includes normal O(n³) parallel version and Strassen algorithm.
> demo: add parallel matrix multiplication

- src/par_iter/mod.rs
- src/par_iter/reduce.rs
- src/par_iter/test.rs
Closes #148.
(The failing tests should be unrelated; they fail on master as well.)
> Match sequential iterator API for comparison-based reducers

- src/par_iter/collect/consumer.rs
- src/par_iter/for_each.rs
- src/par_iter/internal.rs
- src/par_iter/mod.rs
- src/par_iter/noop.rs
- src/par_iter/skip.rs
- src/par_iter/take.rs
- src/par_iter/test.rs
These commits implements `skip` and `take` on exact parallel iterators.
I am very unsure if I have put the bounds checking in the right place; right now it is in `len()`, using the fact that it's `&mut self`. However, maybe there is no guarantee for `len()` to have been called before `with_producer`, in which case we will crash.
I'm a first time contributor (and almost first time user) of Rayon, and most of the code is taken from `enumerate.rs`, so I'm sorry if there are obvious errors here :)
> Fixes issue #147

- src/par_iter/from_par_iter.rs
- src/par_iter/mod.rs
- src/par_iter/string.rs
- src/par_iter/test.rs
- src/prelude.rs
This is a first step toward useful parallel operations on strings.  It
works as an `UnindexedProducer` to split on UTF-8 character boundaries.
> Add ParallelString with par_chars

- src/par_iter/mod.rs
- src/par_iter/test.rs
Working as group which is why the pull request is being initiated early so that we can each merge into this common branch.
First Commit Implements cmp
Uses the existing zip, map, and reduce combinators to implement cmp.
Closes #152
> Fixing Issue 152

- rayon-demo/src/main.rs
- rayon-demo/src/vec_collect.rs
- src/par_iter/chain.rs
- src/par_iter/collect/consumer.rs
- src/par_iter/collect/mod.rs
- src/par_iter/enumerate.rs
- src/par_iter/from_par_iter.rs
- src/par_iter/map.rs
- src/par_iter/mod.rs
- src/par_iter/option.rs
- src/par_iter/range.rs
- src/par_iter/skip.rs
- src/par_iter/slice.rs
- src/par_iter/slice_mut.rs
- src/par_iter/string.rs
- src/par_iter/take.rs
- src/par_iter/vec.rs
- src/par_iter/weight.rs
- src/par_iter/zip.rs
It's now parameterized on the item type, which allows collecting
different things, e.g. `String` (#164) might collect `char` or `&str`.
The `from_par_iter` method is parameterized on `IntoParallelIterator`,
which means `Vec` has to be generalized too, not just exact.  There's
always `collect_into`, and we can eventually do better when Rust gets
specialization.
> Make FromParallelIterator look more like FromIterator

- src/par_iter/vec.rs
There was a comment that we should use `ptr::drop_in_place` once stable,
which happened in Rust 1.8.  We're beyond that minimum already for other
features, so let's go ahead and use it.
> Use drop_in_place in vec's SliceDrain

- .travis.yml
- README.md
Rayon currently requires 1.12.0 to allow building with `impl Trait`
syntax in some of the tests, as they must parse even in normal builds.
Closes #145.
> Document and test the minimum rustc explicitly

- src/par_iter/chain.rs
- src/par_iter/collect/mod.rs
- src/par_iter/test.rs
`ChainIter::drive_unindexed` can't deal with the fake specialization
used by `CollectConsumer`, as it has to directly call `split_off`.  So
we must not report an `opt_len`, and thus iterators with any chaining
can't take advantage of that optimization.
However, it would be a regression if we couldn't even use `collect_into`
with chains, so we need to let that call a direct indexed `drive` again.
So refactor the entry points with `collect_into` calling `drive`, and
still `special_collect_into` calling `drive_unindexed`, with all of
their common code in a new `Collect` wrapper.
Fixes #175.
> Remove the fake specialization on chain collect

- src/par_iter/reduce.rs
A small improvement that makes it possible for the sum loops to optimize.
(Note that floating point reductions are not possible to autovectorize, but integers are.)
Fixes #181
> Add #[inline] on the primitive numeric type impls

- rayon-demo/src/tsp/bench.rs
Rarely, I've seen this case fail with a result that's exactly the
reverse of the expected path.  I suppose there's no harm in going the
other way.  So we just detect if the given path is `lt` when reversed,
and then normalize it before asserting its value.
> tsp: normalize the direction of the benchmarked path

- src/par_iter/chain.rs
- src/par_iter/enumerate.rs
- src/par_iter/filter.rs
- src/par_iter/filter_map.rs
- src/par_iter/find.rs
- src/par_iter/flat_map.rs
- src/par_iter/fold.rs
- src/par_iter/map.rs
- src/par_iter/option.rs
- src/par_iter/range.rs
- src/par_iter/skip.rs
- src/par_iter/slice.rs
- src/par_iter/slice_mut.rs
- src/par_iter/string.rs
- src/par_iter/take.rs
- src/par_iter/test.rs
- src/par_iter/vec.rs
- src/par_iter/weight.rs
- src/par_iter/zip.rs
Nightly started warning that many `use super::internal::*` imports under
`par_iter` were unused -- see rust-lang/rust#38104.  It turns out that
all those modules also had `use super::*`, and `par_iter/mod.rs` has its
own `use internal::*`, so apparently this now adds to what the other
modules get.
But we can't just remove those lines, because it doesn't work for older
rustc.  Instead we can reorder it so `super::internal::*` comes first,
and nothing looks unused to the linter.
> Reorder use super::* / super::internal::*

- src/api.rs
- src/test.rs
- src/thread_pool.rs
Per discussion in https://bugzilla.mozilla.org/show_bug.cgi?id=1323372
We need either this or #185, but not both.
CC @emilio
> Expose the number of threads in the pool and the index of the current thread

- Cargo.toml
- RELEASES.md
This release includes a lot of progress towards the goal of parity with the sequential iterator API, though there are still a few methods that are not yet complete. If you'd like to help with that effort, [check out the milestone](https://github.com/nikomatsakis/rayon/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Parity+with+the+%60Iterator%60+trait%22) to see the remaining issues.
**Announcement:** @cuviper has been added as a collaborator to the Rayon repository for all of his outstanding work on Rayon, which includes both internal refactoring and helping to shape the public API. Thanks @cuviper! Keep it up.
- We now support `collect()` and not just `collect_with()`.
You can use `collect()` to build a number of collections,
including vectors, maps, and sets. Moreover, when building a …
> release v0.6.0

- src/par_iter/chain.rs
- src/par_iter/internal.rs
This method allows the producers to customize the inner loop. This is
useful for iterators that can provide a more efficient inner loop than
the default for loop.
Example: multidimensional arrays.
> Add method fold_with to Producer and UnindexedProducer

- src/par_iter/internal.rs
- src/par_iter/mod.rs
- src/par_iter/range.rs
- src/par_iter/string.rs
- src/par_iter/test.rs
This should give the exact same result at `str::split`, just in parallel!  But we only support a plain `char` for the separator right now, versus the fancy `str::Pattern` trait.  The test cases are taken from the `str::split` docstring, as well as a split on `test.rs` itself for something larger.
> Add a string `par_split` method for `char` separators

- src/par_iter/find_first_last.rs
- src/par_iter/find_first_last/mod.rs
- src/par_iter/find_first_last/test.rs
- src/par_iter/mod.rs
- src/par_iter/test.rs
Fixes #151 
This is my first PR to Rayon, so any and all feedback is welcome.
> Implement find_first/last, position_first/last

- Cargo.toml
Updating allows for rayon to be compiled for fuchsia and emscripten.
> Updated num_cpus dependency

- src/par_iter/find_first_last/mod.rs
- src/par_iter/find_first_last/test.rs
I just found a few compiler warnings I forgot about from find_first/find_last that I went ahead and fixed.
> Fix some compiler warnings from find_first/last

- src/registry.rs
- src/thread_pool/test.rs
`Registry::terminate` was merely setting `terminate_latch`, leaving
sleeping threads in an eternal slumber.  Normally that would just amount
to a resource leak, but `thread_pool::test::workers_stop` will stall
waiting for every thread to stop.  We just need a `tickle` to make sure
every thread will wake up and exit.
Fixes #200.
> Give one last tickle to terminated registries

- src/configuration.rs
- src/registry.rs
- src/thread_pool/mod.rs
- tests/run-pass/named-threads.rs
This PR adds support for specifying names for rayon threads, and fixes issue #142.
Most notable things are:
- `Registry::new` takes the entire `Configuration`, not just the number of threads
- The thread name is `format!("{}{}", name, i)`
I found it difficult to test the thread naming. Any ideas?
> Add support for naming threads

- src/configuration.rs
- src/registry.rs
- tests/run-pass/named-threads.rs
This was missed while merging #202 😄
> Rename `base_thread_name` to `thread_name`

- src/par_iter/internal.rs
- src/par_iter/range.rs
- src/par_iter/string.rs
Our `string::ParSplit` can write a better `fold_with` than its iterator, because it can bypass the chain-Option iterator logic.  However, this duplicates some slightly tricky logic if we still keep the trait requirement for `IntoIterator`.  We can drop that and just *require* `fold_with`, without a default implementation.  It's trivial now for those that do have `IntoIterator` to use `Folder::consume_iter`.
> Require `UnindexedProducer::fold_with` without `IntoIterator`           

- src/par_iter/mod.rs
- tests/compile-fail/no_send_par_iter.rs
All three of these methods lacked any constraints on their output types,
even though it has to be `Send` for the returned adaptor to itself be a
`ParallelIterator`.  This sometimes leads to error messages in usage
that give no indication that missing `Send` is the real problem.  If we
add that requirement up front, it should be a more helpful error.
Fixes #204.
> Require `Send` output in `map`, `cloned`, `filter_map`

- src/par_iter/string.rs
- src/par_iter/test.rs
Both `par_split` and `par_split_terminator` can now accept `Fn(char) -> bool` for the separator, in addition to a simple `char`.  This is somewhat modeled after the standard library `Pattern`, but that's not stable so we can't use it directly.  From this, `par_split_whitespace` follows easily.
This also adds a "private" method to `ParallelString`, as suggested by @bluss, so we can add methods without worrying about breaking third-party implementations.
Fixes #133.
> Add `par_split(Fn)` and `par_split_whitespace` for strings

- src/par_iter/internal.rs
It was documented that the index must be strictly less than the length,
but in practice it may also equal the length, especially in the current
`ChainProducer` that often carries a zero-length side around.
Fixes #215.
> doc: the `Producer::split_at` index can equal the length

- src/par_iter/mod.rs
- src/par_iter/test.rs
Lexicographic comparisons are entirely decided by the first unequal
elements, which `find_first` can pull out for us.
> Use `find_first` to short-circuit `cmp` and `partial_cmp`

- src/par_iter/chain.rs
- src/par_iter/enumerate.rs
- src/par_iter/internal.rs
- src/par_iter/map.rs
- src/par_iter/mod.rs
- src/par_iter/option.rs
- src/par_iter/range.rs
- src/par_iter/rev.rs
- src/par_iter/slice.rs
- src/par_iter/slice_mut.rs
- src/par_iter/test.rs
- src/par_iter/vec.rs
- src/par_iter/weight.rs
- src/par_iter/zip.rs
Fixes #150, using the approach @nikomatsakis suggested. A few notes on problems mentioned in that issue:
* Producer iterator types are required to implement `ExactSizeIterator` as well as `DoubleEndedIterator` (should be fine since producers are based on exact-size parallel iterators anyway).
* We were able to use `Range` inside `enumerate()` after all: since the iterators usable by `enumerate()` are required to be exact-size, their max index is actually `usize::MAX - 1`.
* I wrote a wrapper around `Chain` to make it an `ExactSizeIterator`. This isn't actually correct if adding the lengths of the iterators overflows, but it will work for most cases. This was already an issue anyway, since the same issue could cause issues for `Chain` as an `IndexedParallelIterator`
> Implement rev

- rayon-demo/src/fibonacci/mod.rs
- rayon-demo/src/quicksort/bench.rs
- src/iter/internal.rs
- src/iter/mod.rs
- src/iter/splitter.rs
- src/iter/test.rs
- src/lib.rs
- src/range.rs
- src/string.rs
This takes two arguments, the data and a closure to split it, and
implements a `ParallelIterator`.  The data will be divided using the
usual `par_iter` splitting heuristics, then may be mapped, reduced, etc.
however is needed.
The `fibonacci` and `quicksort` demos have been updated with `split`
examples, where the former splits `n` into `n-2` and `n-1`, and the
latter performs a sorting partition before splitting its slice.
> Add a new `rayon::split` to create arbitrary parallel iterators

- README.md
When I was first learning about work stealing, the mention of "a central queue" here confused me.  I hope this expanded description is clearer.
[Rendered](https://github.com/mbrubeck/rayon/blob/docs/README.md#how-it-works-work-stealing)
> Minor edits to description of work-stealing in README

- src/iter/flat_map.rs
- src/iter/test.rs
Usually in `flat_map`, the cost is infinite, so `FlatMapFolder` doesn't
expect to ever see more than one item.  However, `UnindexedProducer` is
only using the thief splitter, never weights, so it doesn't notice the
cost and may in fact have multiple items in this fold.
It did handle this possibility just in case, but the order of the reduce
arguments were swapped, with the new result before the previous.  This
is easily seen with collect, where items show up in the wrong order.
(Generally, we require that ops are associative, but not commutative.)
> Fix the reduction order of flat_map

- src/iter/collect/mod.rs
- src/iter/collect/test.rs
`CollectConsumer` uses unsafe code but is not intended to "trust"
the producers, which are not generally unsafe, so it should be
ready for anything.
cc #53
> add test that drives the collect-consumer, producing too many values

- src/iter/README.md
- src/iter/collect/consumer.rs
- src/iter/collect/mod.rs
- src/iter/enumerate.rs
- src/iter/filter.rs
- src/iter/filter_map.rs
- src/iter/find.rs
- src/iter/find_first_last/mod.rs
- src/iter/flat_map.rs
- src/iter/fold.rs
- src/iter/for_each.rs
- src/iter/from_par_iter.rs
- src/iter/internal.rs
- src/iter/map.rs
- src/iter/mod.rs
- src/iter/noop.rs
- src/iter/reduce.rs
- src/iter/rev.rs
- src/iter/skip.rs
- src/iter/splitter.rs
- src/iter/take.rs
- src/iter/weight.rs
I picked the most obvious letters to me. Mapping operations; `F` for function, for anything that returns a bool; `P` for predicate, etc. I made sure to change the associated lifetimes to match up and fix any formatting changes. Let me know if there's anything you'd like to change. 
#249
> Shorten type param names

- src/iter/map.rs
- src/iter/mod.rs
- src/iter/reduce.rs
- src/lib.rs
- src/private.rs
- src/slice.rs
- src/string.rs
This moves the `private::PrivateMarker` to the top level, and adds `private_decl!{}` and `private_impl!{}` for us to apply this in a uniform way.
This marks several more traits as private using the new macros.  `string::Pattern` is only meant to be used by the already-private `ParallelString`.  I think `iter::MapOp`, and `iter::ReduceOp` should get completely hidden for #228, but we can at least close their implementations until then.  Similarly, I'd like the chunks traits to look more like `ParallelString`, but closing them off now is an incremental step.
I believe all remaining traits are desirable to leave open for outside implementations.
> Generalize the private trait marker and use it more

- rayon-core/src/configuration.rs
- rayon-core/src/registry.rs
- tests/run-pass/stack_overflow_crash.rs
Unfortunately I haven't been able to find a neat way to unit test this.
My first attempt was to force a stack overflow via recursion, but that segfaults the entire process (less than ideal for a unit test).
Using `getrlimit()` only seemed to return the system wide limits.
It might be possible to do something with pthread functions...
I checked via valgrind using the following command:
`valgrind --trace-children=yes --tool=drd --show-stack-usage=yes cargo test --lib -- --nocapture stack_size 2>&1 | grep stack`
Fixes #179
> add stack_size parameter to Configuration (fixes #179)

- src/iter/collect/mod.rs
- src/iter/from_par_iter.rs
- src/iter/mod.rs
Before, when this trait was under the private `mod from_par_iter`,
rustdoc copied its documentation to the reexport paths in both `iter`
and `prelude`.  It was the only thing in `prelude` that didn't *look*
like a reexport, and its relative links were broken in this path.
Now that `iter::FromParallelIterator` is the actual definition path, it
shows up as a proper reexport under the `prelude`.
> Move `FromParallelIterator` directly into `mod iter`

- src/iter/collections.rs
- src/iter/mod.rs
- src/iter/test.rs
- src/prelude.rs
- src/slice.rs
I started with a simple refactoring, and kept going...
- The former `ToParallelChunks`/`Mut` are now just part of `ParallelSlice`.
- A new `par_windows` is a parallel version of the standard `windows`.
- The slice iterator *types* are no longer part of the prelude.  We usually just want traits here.
- The slice iterator types are now renamed to mirror those in `std::slice`
- `Iter`, `IterMut`, `Chunks`, `ChunksMut`, `Windows`
- ~~The distinct producer types weren't necessary - just implement `Producer` on the iterators.~~
- The private producers are now named `IterProducer`, `IterMutProducer`, etc.
> Refactor slice extensions into a ParallelSlice trait

- rayon-demo/src/pythagoras/mod.rs
- src/iter/mod.rs
- src/iter/product.rs
- src/iter/reduce.rs
- src/iter/sum.rs
- src/iter/test.rs
`SumOp` is replaced by `Sum + Add`, `ProductOp` by `Product + Mul`, and `ReduceOp` is now hidden.
Technically, we could get by without `Add`/`Mul`, but it's easier this way, and I find it unlikely that these would ever be missing from something that implements `Sum`/`Product`.
Fixes #252.
> Use the standard Sum/Product traits

- src/iter/flat_map.rs
- src/iter/for_each.rs
In `FlatMapConsumer::split_at`, we can just pass it down to the base
consumer's `split_at`.  Avoiding the double `split_off_left()` here
might improve the indexing resolution of `find_first`/`last`, but is
otherwise just a small optimization.
In `ForEachConsumer::split_at`, we only need one `split_off_left()` to
get a copy of `self`, and then we can just use `self` for the second.
> Remove redundant split_off_left() calls

- src/iter/chain.rs
- src/iter/test.rs
Since `UnindexedConsumer: Consumer`, `Chain::drive_unindexed` can work just
fine with collect's consumer.  We know the length in this case, so we can
use the more precise `Consumer::split_at`, and this is fine for regular
unindexed consumers too.
This also adds a more explicit test of chain collect, as the prior fix and
testing in #176 didn't actually appear to exercise this case as intended.
> Make Chain work with specialized collect

- src/iter/mod.rs
- src/iter/splitter.rs
With all the other renaming lately, this one stood out as the last
iterator type with a redundant "Parallel" in its name.  While this one
doesn't have a sibling in `std::iter`, it still fits better with the
rest of our iterators when called `rayon::iter::Split`.
> Rename iter::ParallelSplit to iter::Split

- rayon-core/src/configuration.rs
The previous comment dates from a time when `Arc` was not used.
> fix the documentation for Configuration::panic_handler

- rayon-core/src/registry.rs
- rayon-core/src/thread_pool/mod.rs
- rayon-core/src/thread_pool/test.rs
This adds a guard structure around the `Registry::new` thread startup,
which terminates the whole registry if we can't complete it.  It now
returns a boxed error if `Builder::spawn` fails, and should deal better
with any panics, like from the user's `thread_name` callback.
Fixes #205.
> Terminate new registries after panic or spawn errors

- Cargo.toml
- RELEASES.md
- rayon-core/Cargo.toml
This release marks the first step towards Rayon 1.0. **For best
performance, it is important that all Rayon users update to at least
Rayon 0.7.** This is because, as of Rayon 0.7, we have taken steps to
ensure that, no matter how many versions of rayon are actively in use,
there will only be a single global scheduler. This is achieved via the
`rayon-core` crate, which is being released at version 1.0, and which
encapsulates the core schedule APIs like `join()`. (Note: the
`rayon-core` crate is, to some degree, an implementation detail, and
not intended to be imported directly; it's entire API surface is
mirrored through the rayon crate.)
We have also done a lot of work reorganizing the API for Rayon 0.7 in
preparation for 1.0. The names of iterator types have been changed and
reorganized …
> Release 0.7

- rayon-demo/src/vec_collect.rs
- src/delegate.rs
- src/iter/README.md
- src/iter/chain.rs
- src/iter/collect/mod.rs
- src/iter/enumerate.rs
- src/iter/filter.rs
- src/iter/filter_map.rs
- src/iter/fold.rs
- src/iter/len.rs
- src/iter/map.rs
- src/iter/mod.rs
- src/iter/rev.rs
- src/iter/skip.rs
- src/iter/take.rs
- src/iter/test.rs
- src/iter/zip.rs
- src/option.rs
- src/prelude.rs
- src/range.rs
- src/slice.rs
- src/vec.rs
This reduces our iterator traits to just `ParallelIterator` and
`IndexedParallelIterator`.  The bounded and exact iterators had some
theoretical use, but in practice the only distinction we use today is
whether something can be indexed.
The `upper_bound` method is totally removed.  The rest of the methods in
the removed traits are now merged into `IndexedParallelIterator`.
Fixes #229.
Closes #259.
> Remove bounded and exact iterators

- src/iter/cloned.rs
- src/iter/inspect.rs
- src/iter/map.rs
- src/iter/mod.rs
- tests/compile-fail/no_send_par_iter.rs
Before, the public API exposed the fact that these shared a common
`MapOp` implementation.  Now they are distinct iterator types with
fully custom implementations.
> Split into separate map/clone/inspect iterators

- src/iter/mod.rs
Find and Position are meant to be kept indefinitely to guide them to the right thing.
> Revert Subset of Remove Deprecated Interfaces

- src/iter/mod.rs
It's not fully clear that "first" in `find_first` and `position_first`
is referring to the first in the sequential order of items, rather than
the temporally first match found anywhere like `find_any`.  This update
emphasizes that we mean sequentially first.
There shouldn't be the same issue in `find_last` and `position_last`, as
there's no reason to look for a "temporally last" match, but those docs
are also updated just to keep similarity to the "first" methods.
> Clarify the ordering of find_first etc.

- src/iter/from_par_iter.rs
- src/iter/test.rs
This collects a `Cow::Owned` for any borrowed type with `ToOwned`, where
the associated `Owned` type implements `FromParallelIterator`.
Note, the standard library only has `FromIterator` for `Cow<'a, str>` and
`Cow<'a, [T]>`, because no one thought to add a blanket implementation
before it was stabilized.
> impl FromParallelIterator for Cow

- src/iter/mod.rs
- src/iter/test.rs
- src/iter/while_some.rs
- src/option.rs
- src/result.rs
The new `while_some` filters for `Some` values, and halts if it encounters any
`None`.  This is inspired by `Itertools::while_some`, although being parallel
means it doesn't consider the order.
Using this, we can implement a short-circuiting collect for `Option` and
`Result` like the standard library, returning just `None` or `Err` respectively
if any such item is found in the iterator.  Since this operates in parallel,
it's not deterministic which items will have already been visited, nor which
`Err` will be returned if there are multiple.
> Add while_some; impl FromParallelIterator for Option/Result

- src/iter/collect/consumer.rs
- src/iter/fold.rs
- src/iter/for_each.rs
- src/iter/internal.rs
- src/iter/noop.rs
- src/iter/product.rs
- src/iter/reduce.rs
- src/iter/sum.rs
- src/iter/test.rs
`FoldConsumer` and `FoldFolder` never got their `fn full`, probably
because these features were developed near the same time.  They just
need to pass the call down to their base consumer/folder.
> Fold should pass the full check to its base

- rayon-core/Cargo.toml
- rayon-core/src/lib.rs
- rayon-core/src/registry.rs
In #195 I've laid out problems with Crossbeam's current implementation of the Chase-Lev deque.
Coco is a new crate that will bring lock-free data structures and a better epoch-based GC. At the moment it provides a stack and a deque. It's deque outperforms Crossbeam's deque and collects garbage more eagerly.
Performance should be more-or-less identical to the `deque` crate.
cc @cuviper 
Benchmark:
```
name                                                     out ns/iter  out_coco ns/iter  diff ns/iter   diff %
factorial::factorial_iterator                            21,253,985   21,257,250               3,265    0.02%
factorial::factorial_join                                10,297,681   10,205,071             -92,610   -0.90%
factorial::factorial_par_iter …
```
> Replace deque crate with coco

- src/iter/fold.rs
- src/iter/map_with.rs
- src/iter/mod.rs
- src/iter/test.rs
These provide a means to use additional values with a parallel iterator,
without excessive cloning nor requiring `Sync`.  This sort of need has
most often come up for using `mpsc::Sender`.
```rust
fn map_with<F, T, R>(self, init: T, map_op: F) -> MapWith<Self, T, F>
where F: Fn(&mut T, Self::Item) -> R + Sync,
T: Send + Clone,
R: Send;
fn fold_with<F, T>(self, init: T, fold_op: F) -> FoldWith<Self, T, F>
where F: Fn(T, Self::Item) -> T + Sync,
T: Send + Clone;
```
> Add map_with and fold_with

- rayon-core/src/future/mod.rs
- rayon-core/src/lib.rs
- rayon-core/src/registry.rs
- rayon-core/src/spawn/mod.rs
- rayon-core/src/spawn/test.rs
- rayon-core/src/thread_pool/mod.rs
- src/lib.rs
Between the `_async` and `_future` suffixes, there was quite a zoo of
possibilities:
- `Scope::spawn`
- `Scope::spawn_future`
- `::spawn_async`
- `::spawn_async_future`
After this PR, there are now two orthogonal concepts. First, what
**scope** are you spawning the task into? If you use the free-standing
functions, like `rayon::spawn()`, or methods on a thread-pool, like
`pool.spawn_future()`, that is the "static" or "global" scope, and
hence no stack references are allowed. Otherwise, if you create a scope
using `scope()`, then when you do `scope.spawn()` it is spawned into
that scope.
Second, are you spawning a task for side-effects (`spawn()`) or to
produce a result (`spawn_future()`).
**NB:** Everything but `Scope::spawn()` remains "unstable" in this PR.
> RFC: stop using the `_async` terminology

- .travis.yml
- appveyor.yml
I enabled the unstable feature on stable because it's unstable only for `Rayon`(doesn't contain Rust nightly features). At least in Appveyor, `1.12.0` with the unstable feature enabled fails to build - that's why there is no matrix for `1.12.0` + `FEATURES=unstable`.
You can see the status of these builds:
- Windows: https://ci.appveyor.com/project/lilianmoraru/rayon
- Linux/macOS: https://travis-ci.org/lilianmoraru/rayon
On Windows, nightly fails and I don't know why(I don't have a Windows machine to test locally).
> Add Windows CI(Appveyor) and enable unstable features in Travis on stable Rust

- src/iter/test.rs
- src/lib.rs
- src/prelude.rs
- src/slice.rs
- src/split_producer.rs
- src/str.rs
A recent thread on [internals] got me thinking whether we could avoid the `private_impl!{}` hack after all.  With a few extra constraints, this does work!
[internals]: https://internals.rust-lang.org/t/pre-rfc-do-not-allow-public-structs-in-private-modules/5156
With `ParallelString: Borrow<str>`, we can provide default implementations of all its methods, and should be free to add new methods the same way.  Then a blanket `impl` only has to meet the constraints, so there's also less repetition defining these methods.
Similarly `ParallelSlice<T: Sync>: Borrow<[T]>` works for slices, and a new `ParallelSliceMut<T: Send>: BorrowMut<[T]>` for mutable slices.  The latter is also added to the prelude.
I also considered `AsRef` and `AsMut`, which are very similar to borrows, but I decided against …
> Reduce use of the pub-in-private hack

- rayon-demo/src/main.rs
- rayon-demo/src/str_split.rs
- src/str.rs
I wasn't sure how well this actually performs, so a benchmark is in order.  I've added a few annotations to help inlining, but otherwise it seems to be pretty good!
test str_split::parallel_space_char ... bench:     555,040 ns/iter (+/- 30,003)
test str_split::parallel_space_fn   ... bench:     547,287 ns/iter (+/- 9,644)
test str_split::serial_space_char   ... bench:   2,236,302 ns/iter (+/- 52,654)
test str_split::serial_space_fn     ... bench:   2,235,842 ns/iter (+/- 79,746)
test str_split::serial_space_str    ... bench:   2,714,414 ns/iter (+/- 61,583)
(on my i7-2600 with 4 cores / 8 threads)
> Add a benchmark of `ParallelString::par_split`

- src/iter/chain.rs
- src/iter/filter.rs
- src/iter/filter_map.rs
- src/iter/flat_map.rs
- src/iter/fold.rs
- src/iter/inspect.rs
- src/iter/map.rs
- src/iter/map_with.rs
- src/iter/mod.rs
- src/iter/splitter.rs
- src/iter/unzip.rs
- src/slice.rs
- src/str.rs
If the parallel iterators are themselves always `Send`, then we can use
`join` in implementing `Chain::drive` and `drive_unindexed`.  This
resolves the current sequence point between each side, as they can now
run in parallel if a thread is available to steal it.
The main fallout of that new requirement is that closures we accept must
now be `Send` too, in addition to the existing `Sync` requirement.  It's
not strictly necessary in all cases, like `for_each` that doesn't create
a parallel iterator itself, but it seems nicer to apply a consistent
requirement.
Fixes #342.
> Add `ParallelIterator: Send` to join `Chain`

- rayon-core/src/lib.rs
- rayon-core/src/log.rs
I hope this PR doesn't appear like bikeshedding, but I believe `RAYON_RS_NUM_THREADS` is a better, more mnemonic name for the environment variable compared with `RAYON_RS_NUM_CPUS`.
Reasons:
1. It corresponds to what the environment variable is supposed to be controlling, namely the *number of threads*; from `rayon-core/src/lib.rs`:
```rust
pub struct Configuration {
/// The number of threads in the rayon thread pool.
/// If zero will use the RAYON_RS_NUM_CPUS environment variable.
/// If RAYON_RS_NUM_CPUS is invalid or zero will use the default.
num_threads: usize,
...
}
```
2. The variable name would correspond to what OpenMP is using, which is `OMP_NUM_THREADS`. Since rayon is very likely going to be used for the same purposes that OpenMP is used in other languages, this would be a …
> Introduce RAYON_NUM_THREADS and RAYON_LOG env vars

- rayon-core/src/sleep/mod.rs
Fix #343: Rayon 0.7.0: unbounded spins in Sleep::no_work_found
> Fix #343: Rayon 0.7.0: unbounded spins in Sleep::no_work_found

- rayon-core/Cargo.toml
Reverts nikomatsakis/rayon#349
That was hasty and I knew I would come to regret it. I only wanted to issue the fix for #343, but there have been other changes to rayon-core in the meantime, and I suspect a v1.1 release would be better for the total set.
> Revert "bump rayon core release to v1.0.1 to reflect fix to #343"

- rayon-core/src/thread_pool/mod.rs
This addresses #235 
Let me know if this is along the lines of what you were looking for. I made an assumption that `rayon::join` called inside of ThreadPool's `spawn` methods will also execute inside of the ThreadPool context, like `install`. If this isn't the case, I'll alter the second example and amend this commit. The example for `spawn_future_async` is based on code from your test cases.
> Threadpool documentation

- rayon-core/Cargo.toml
- rayon-core/src/join/mod.rs
- rayon-core/src/lib.rs
- rayon-core/src/log.rs
- rayon-core/src/registry.rs
- rayon-core/src/scope/mod.rs
- rayon-core/src/thread_pool/mod.rs
These introduce two new core APIs that were suggested by @bholley for use in Servo (Stylo, in particular). They are insta-stable because I would want to make a public release so that Servo can make use of them.
The APIs are:
- Introduce a new "breadth-first" scheduling mode that can be enabled per thread-pool. In breadth-first mode, both the current thread *and* stealer threads draw from the bottom of the deque. Depending on your workload, this may be desirable (in the case of stylo, it leads to better cache reuse). Users can opt into breadth-first mode by adjusting the configuration.
- Introduce a new `spawn_tail()` API that is intended to be used for the *last* task that will be spawned. It is intended as a slight optimization on calling `spawn` and then immediately returning from the …
> mock up `breadth_first` and `spawn_tail`

- Cargo.toml
- RELEASES.md
- rayon-core/Cargo.toml
- Added the `map_with` and `fold_with` combinators, which help for
passing along state (like channels) that cannot be shared between
threads but which can be cloned on each thread split.
- Added the `while_some` combinator, which helps for writing short-circuiting iterators.
- Added support for "short-circuiting" collection: e.g., collecting
from an iterator producing `Option<T>` or `Result<T, E>` into a
`Option<Collection<T>>` or `Result<Collection<T>, E>`.
- Support `FromParallelIterator` for `Cow`.
- Removed the deprecated weight APIs.
- Simplified the parallel iterator trait hierarchy by removing the
`BoundedParallelIterator` and `ExactParallelIterator` traits,
which were not serving much purpose.
- Improved documentation.
- Added some missing `Send` impls.
- Fixed some small bugs.
- …
> release rayon v0.8.0

- src/iter/chain.rs
- src/iter/cloned.rs
- src/iter/enumerate.rs
- src/iter/filter.rs
- src/iter/filter_map.rs
- src/iter/flat_map.rs
- src/iter/fold.rs
- src/iter/inspect.rs
- src/iter/len.rs
- src/iter/map.rs
- src/iter/map_with.rs
- src/iter/rev.rs
- src/iter/skip.rs
- src/iter/take.rs
- src/iter/while_some.rs
- src/iter/zip.rs
- tests/compile-fail/must_use.rs
This follows the example of the standard library, even so lazy as to
steal their exact message about laziness.
cc #365
> Add `#[must_use]` attributes to iterator adaptors

- src/iter/find_first_last/mod.rs
- src/iter/find_first_last/test.rs
- src/lib.rs
It's possible to generate giant iterators in Rayon, and these tests show
that they can still be short-circuited properly in find operations.
> Add `find_first` and `find_last` tests on a giant range

- .travis.yml
- Cargo.toml
- README.md
- appveyor.yml
- examples/cpu_monitor.rs
- rayon-core/Cargo.toml
- rayon-core/src/lib.rs
- rayon-core/src/scope/mod.rs
- rayon-core/src/thread_pool/mod.rs
- rayon-demo/Cargo.toml
- src/lib.rs
- src/test.rs
This branch documents our semver policy and also makes it less convenient to use unstable features. They are no longer exposed as a cargo feature, but instead require `RUSTFLAGS=--cfg unstable`. 
Fixes #369.
> adopt stricter semver policy around unstable features

- .travis.yml
- Cargo.toml
- README.md
- appveyor.yml
- examples/cpu_monitor.rs
- rayon-core/Cargo.toml
- rayon-core/src/lib.rs
- rayon-core/src/scope/mod.rs
- rayon-core/src/spawn/mod.rs
- rayon-core/src/spawn/test.rs
- rayon-core/src/thread_pool/mod.rs
- rayon-demo/Cargo.toml
- src/lib.rs
- src/test.rs
Building on #368, this branch stabilizes the `spawn` API and a bunch of convenience methods in `ThreadPool`:
- `rayon_core::ThreadPool::join`
- `rayon_core::ThreadPool::scope`
- `rayon_core::ThreadPool::spawn`
- `rayon_core::spawn` -- runs async task in current (or global) thread-pool
The only one that enables something fundamentally new that wasn't available in a stable API is `rayon_core::spawn`. The `ThreadPool` APIs are convenience wrappers around other APIs.
The following APIs remain **unstable**:
- `ThreadPool::global` -- I don't know that we want to expose th `Arc`
here, although it's no real commitment
- everything related to futures -- that is all planned to change
> Stabilize spawning an asynchronous task and convenience methods on ThreadPool

- Cargo.toml
- README.md
- RELEASES.md
- rayon-core/Cargo.toml
- The following core APIs are being stabilized:
- `rayon::spawn()` -- spawns a task into the Rayon threadpool; as it
is contained in the global scope (rather than a user-created
scope), the task cannot capture anything from the current stack
frame.
- `ThreadPool::join()`, `ThreadPool::spawn()`, `ThreadPool::scope()`
-- convenience APIs for launching new work within a thread-pool.
- The various iterator adapters are now tagged with `#[must_use]`
- Parallel iterators now offer a `for_each_with` adapter, similar to
`map_with`.
- We are adopting a new approach to handling the remaining unstable
APIs (which primarily pertain to futures integration). As awlays,
unstable APIs are intended for experimentation, but do not come with
any promise of compatibility (in other words, we might change them …
> release rayon 0.8.1, rayon-core 1.2.0

- README.md
The version must be enclosed with double quotes, otherwise you get something like:
```
error: failed to parse manifest at `/home/stjepan/work/par-sort/Cargo.toml`
Caused by:
could not parse input as TOML
Caused by:
expected newline, found a period at line 10
```
> Fix dependencies block in readme

- tests/compile-fail/rc_return.rs
It seems that current rustc is now only reporting one error for `Rc`
returned in both `join` arguments.  We can split our test into two lines
to explicitly check the failure in each argument position.
> Split up the test of join returning Rc

- tests/compile-fail/must_use.rs
After rust-lang/rust#42756, the error message no longer contains the
string "unused result", but "must be used" works before and after.
> test: update the `unused_must_use` error pattern

- rayon-demo/src/main.rs
- rayon-demo/src/sort.rs
- src/slice/mergesort.rs
- src/slice/mod.rs
- src/slice/quicksort.rs
- src/slice/test.rs
- tests/run-pass/sort-panic-safe.rs
This PR introduces 6 new methods on mutable slices:
1. `par_sort`
2. `par_sort_by`
3. `par_sort_by_key`
4. `par_sort_unstable`
5. `par_sort_unstable_by`
6. `par_sort_unstable_by_key`
The first three methods perform stable sorting (it allocates a temporary buffer), and the last three perform unstable sorting (it is in-place). As a rule of thumb, unstable sorting is generally faster.
cc @cuviper @m4b
Fixes #376 
The implementation is based on the one in libstd - it is a mixture of plain mergesort and timsort. An important characteristic of the algorithm is that it identifies pre-sorted intervals in advance and only then merges them.
The parallel variant divides the slice into multiple chunks and sorts them in parallel. After that it concatenates adjacent chunks if they're parts of greater …
> Add parallel sorts

- rayon-demo/src/quicksort/mod.rs
- rayon-demo/src/sort.rs
This adds apples-to-apples benchmarks for the new `par_sort*` methods
against the existing `merge_sort` and `quick_sort` demo implementations.
We should have done this as homework for #379.
Results on i7-7700k (4 cores, disabled h/t) grouped by input:
```
test sort::demo_merge_sort_ascending           ... bench:     251,556 ns/iter (+/- 14,797) = 1590 MB/s
test sort::par_sort_ascending                  ... bench:      32,101 ns/iter (+/- 7,709) = 12460 MB/s
test sort::par_sort_unstable_ascending         ... bench:      25,748 ns/iter (+/- 142) = 15535 MB/s
test sort::demo_merge_sort_descending          ... bench:     178,367 ns/iter (+/- 12,319) = 2242 MB/s
test sort::par_sort_descending                 ... bench:      52,579 ns/iter (+/- 7,141) = 7607 MB/s
test …
```
> Benchmark the demo sorts with the new par_sort*

- Cargo.toml
- README.md
- RELEASES.md
- `ParallelSliceMut` now has six parallel sorting methods with the same
variations as the standard library.
- `par_sort`, `par_sort_by`, and `par_sort_by_key` perform stable sorts in
parallel, using the default order, a custom comparator, or a key extraction
function, respectively.
- `par_sort_unstable`, `par_sort_unstable_by`, and `par_sort_unstable_by_key`
perform unstable sorts with the same comparison options.
> Release rayon 0.8.2

- Cargo.toml
- src/iter/mod.rs
- src/iter/test.rs
- src/lib.rs
- src/par_either.rs
We added a bare `Either` type for `partition_map`, but that's not really a type that belongs in Rayon.  The `either` crate has a stable implementation of `Either` for everyone to share.
While we're at it, `Either` implements pass-throughs for `Iterator` and `Extend`, so we can do the same for `ParallelIterator` and `ParallelExtend`.
> Use the either crate for `Either`

- src/slice/mod.rs
These examples were just copied from the docs for `sort` and `sort_unstable`.
> Add examples for par_sort*

- ci/alt-core/Cargo.toml
- ci/highlander/Cargo.toml
- rayon-demo/Cargo.toml
These crates are not intended to be published.
> Disable accidental publish for the unpublished crates

- rayon-core/src/lib.rs
These fields contain a closure, not a string.
```rust
extern crate rayon;
fn main() {
println!("{:?}", rayon::Configuration::default().exit_handler(|_| {}));
}
```
```
Configuration { num_threads: 0, get_thread_name: None, panic_handler: None, stac
k_size: None, start_handler: None, exit_handler: Some("<closure>"), breadth_firs
t: false }
```
```
Configuration { num_threads: 0, get_thread_name: None, panic_handler: None, stac
k_size: None, start_handler: None, exit_handler: Some(<closure>), breadth_first:
false }
^^^^^^^^^
```
> Remove quotes around "<closure>" in Configuration's debug

- rayon-demo/src/tsp/mod.rs
I don't know if you want to take it a step further and remove `try!` in the library code, but for now I just removed it from the demo.
Fixes #419
> Demo cleanup

- src/iter/mod.rs
In sum, we need to be able to compute Item+Item->S as well as S+S->S.
> Clarify signatures of sum and product

- rayon-core/Cargo.toml
- rayon-core/src/lib.rs
- rayon-futures/Cargo.toml
- rayon-futures/src/lib.rs
Should close #424 - I've used some shorter version links for the docs, but if I should just make these exactly what version is specified in the Cargo.toml I can change it, those versions just don't have any published docs yet and making a PR with links that 404'd didn't feel right (but perhaps this is totally fine)
> Add html_root_url for core and futures, with a reminder in Cargo.toml

- src/iter/interleave.rs
- src/iter/mod.rs
- src/iter/test.rs
For parity with itertools, interleave() should alternately produce
elements from two given iterators. Once one of the iterators run out,
elements should just be drawn from the other until both are exhausted.
This is from #384
> Implement interleave()

- src/iter/mod.rs
- src/iter/test.rs
- src/iter/zip_eq.rs
- tests/compile-fail/must_use.rs
This replaces #389, and is much the same. Re-implemented `zip_eq` using a `ZipEq` struct that is a wrapper around `Zip` to better align `zip_eq` with the adapters present in `rayon`, `itertools`, and the standard library.
Closes #386, as I believe it has been decided to not implement `zip_longest`.
@cuviper it was unclear from your comments where you wanted additional documentation. Please advise and I will update.
> Add zip_eq adapter to IndexedParallelIterator (ZipEq struct version)

- rayon-core/src/internal/task.rs
- rayon-core/src/job.rs
- rayon-core/src/registry.rs
- rayon-core/src/scope/internal.rs
- rayon-core/src/scope/mod.rs
- rayon-core/src/scope/test.rs
- rayon-core/src/thread_pool/mod.rs
- rayon-core/src/thread_pool/test.rs
This is a **breaking change** to `rayon-core`, necessary for soundness.
- `Scope::spawn` now requires `Send` for the closure.  Fixes #430.
- `ThreadPool::install` now requires `Send` for the return value.
- (unstable) `internal::Task` now requires `Send + Sync` instead of just
`Send`, so its use of `Arc` properly implements `Send` and `Sync` too.
> Tighten Send and Sync requirements

- src/iter/interleave.rs
- src/iter/interleave_shortest.rs
- src/iter/mod.rs
- src/iter/test.rs
- tests/compile-fail/must_use.rs
Add interleave_shortest() to IndexedParallelIterator that acts like
interleave, except it terminates as soon as one of the iterators is
exhausted.
The other part of/Fixes #384
> Implement interleave_shortest()

- Cargo.toml
- rayon-core/Cargo.toml
- rayon-core/README.md
- rayon-futures/Cargo.toml
- src/lib.rs
> Add Crate level documentation and Cargo attributes

- src/iter/mod.rs
- src/range.rs
Hi
I wanted to add examples to the docs. My first example works as I expected.
My second example behaves very strange. It compiles when I use `i32` as the type of the `Range<T>`.
With any other type such as `usize`, `u64` or `i64` it does not compile.
Do you have an idea how to fix it?
Regards
---
Error message:
```
---- src/range.rs - range::Iter (line 23) stdout ----
error[E0599]: no method named `zip` found for type `rayon::range::Iter<i64>` in the current scope
--> src/range.rs:6:20
|
6 |                   .zip(0..25)
|                    ^^^
|
= note: the method `zip` exists but the following trait bounds were not satisfied:
`&mut rayon::range::Iter<i64> : std::iter::Iterator`
```
> Add a examples to the module docs

- src/iter/mod.rs
- src/iter/rev.rs
- src/iter/zip.rs
- src/lib.rs
Added documentation for all iter traits and structs. Updated links to par_iter and par_iter_mut so they link directly to the methods (previously they linked to the trait page, not the specific method).
> Added documentation for iter types and structs

- rayon-core/src/latch.rs
- rayon-core/src/registry.rs
- rayon-core/src/thread_pool/mod.rs
- rayon-core/src/thread_pool/test.rs
`Registry::in_worker()` now calls a distinct `Registry::in_worker_cross`
when a `WorkerThread` *is* found for the current thread, but it's not
part of this `Registry`'s pool.  We use a new `TickleLatch` which will
awaken a pool when it's set.  Then the current thread can go process
other work from its own pool, possibly going to sleep when idle, and
still be notified when the other pool finishes the new work.
> Solve inter-pool deadlocks

- src/iter/mod.rs
- src/iter/repeat.rs
- src/iter/test.rs
This adds:
- unindexed, infinite `iter::repeat(elt) -> Repeat`
- indexed, finite `iter::repeatn(elt, n) -> RepeatN`
- `Repeat` methods `take(n)` and `zip(iter)` convert to `RepeatN`
This extends #337, opened separately for review since it's a fairly major change.
> Add Repeat and RepeatN

- rayon-core/src/job.rs
- rayon-core/src/join/mod.rs
- rayon-core/src/join/test.rs
- rayon-core/src/lib.rs
- rayon-core/src/registry.rs
- rayon-core/src/scope/mod.rs
- rayon-core/src/thread_pool/mod.rs
- src/iter/internal.rs
- src/lib.rs
This removes the need for tracking thread-id or hacky TLS variables in
the adaptive splitter.  Instead, with `join_context` the parallel
iterator internals are directly informed whether a job is executing on
its original thread or stolen elsewhere.
Note that this is insta-stable since we want to use it ourselves.  We
could hide docs and/or mark it deprecated to approach stability a little
differently than the usual "unstable" feature.
> Introduce `join_context` which tells whether jobs were stolen

- rayon-demo/src/fibonacci/mod.rs
- rayon-demo/src/quicksort/bench.rs
- src/lib.rs
The `split` function creates a `ParallelIterator`, which better
justifies its place in `rayon::iter`.  It's not really used enough to
justify its place in the crate root.
Fixes #432.
> Remove `rayon::split`, leaving only `rayon::iter::split`

- src/iter/intersperse.rs
- src/iter/mod.rs
- tests/compile-fail/must_use.rs
- tests/intersperse.rs
Like the same from `itertools`, this inserts clones of an item between
each item of the parallel iterator.
Closes #385.
> Add an Intersperse adaptor

- src/iter/enumerate.rs
- src/iter/test.rs
- src/vec.rs
- tests/intersperse.rs
- tests/producer_split_at.rs
This takes one of the test cases from `intersperse`, which was very
helpful in poking corner cases, and generalizes it to test all
`Producer`s.
This found a semi-bug with `enumerate().rev()` in the process -- by
zipping with indexes up to `usize::MAX`, reverse iteration has to
iterate a loooong way back.  It now uses the exact length needed.
> Add thorough tests for Producer::split_at

- README.md
The rust book calls this "interior mutability". I think that the two terms were just confused because they sound awfully similar.
First edition: https://doc.rust-lang.org/book/first-edition/mutability.html
Second edition: https://doc.rust-lang.org/book/second-edition/ch15-05-interior-mutability.html#refcellt-and-the-interior-mutability-pattern
> Inherent mutability -> Interior mutablility

- Cargo.toml
- rayon-futures/Cargo.toml
- rayon-futures/README.md
- rayon-futures/src/lib.rs
- rayon-futures/src/test.rs
Fixes #356. See that issue for previous discussion. Ping @cuviper.
The `Notify` API is not fond of `Arc<Notify>` as the old API was with `Arc<Unpark>`. Instead it prefers to take a generic `T: Into<UnsafeNotify>`. Because of the `'static` restriction in the implementation provided by futures-rs we need to roll our own implementation of `UnsafeNotify` and jump through extra hoops to hide the lifetimes in `ScopeFuture`.
The implementation is easier to follow if you consider that it is analogous to [the implementation for `Arc` in futures-rs](https://github.com/alexcrichton/futures-rs/blob/master/src/task_impl/std/mod.rs#L610).
As a bright side, the old `make_unpark` is gone along with the `unpark` field, we now simply reuse the `this` self reference.
There are probably many places where the …
> Bump futures to 0.1.16, move to `Notify` API

- src/iter/empty.rs
- src/iter/mod.rs
- src/iter/once.rs
- src/iter/test.rs
- src/option.rs
- tests/clones.rs
- tests/debug.rs
- tests/producer_split_at.rs
These are simplistic producers, mirroring their `std` namesakes.  They
are essentially just optimized equivalents to iterating `None` and
`Some(x)`, where `empty()` is a ZST, `once()` doesn't need the enum tag
for an `Option`, and neither have the associated enum branches.
> Add "parallel" iter::empty() and iter::once()

- src/iter/mod.rs
> Add documentation examples for parallel iterator methods

- Cargo.toml
- README.md
- RELEASES.md
- rayon-core/Cargo.toml
- rayon-core/src/lib.rs
- rayon-futures/Cargo.toml
- src/lib.rs
- `Configuration` now has a `build` method.
- `ParallelIterator` added `flatten` and `intersperse`, both inspired by
itertools.
- `IndexedParallelIterator` added `interleave`, `interleave_shortest`, and
`zip_eq`, all inspired by itertools.
- The new functions `iter::empty` and `once` create parallel iterators of
exactly zero or one item, like their `std` counterparts.
- The new functions `iter::repeat` and `repeatn` create parallel iterators
repeating an item indefinitely or `n` times, respectively.
- The new function `join_context` works like `join`, with an added `FnContext`
parameter that indicates whether the job was stolen.
- `Either` (used by `ParallelIterator::partition_map`) is now re-exported from
the `either` crate, instead of defining our own type.
- `Either` also now …
> Release rayon 0.9.0 / rayon-core 1.3.0 / rayon-futures 0.1.0

- src/iter/mod.rs
The last remaining examples to do are `map_with` and `fold_with` that I don't really understand.
Could you please explain to me the mecanics ?
> Add examples to the ParallelIterator documentation

- src/iter/mod.rs
> Note how minimum length behaves with combined iterators

- rayon-demo/src/map_collect.rs
- rayon-demo/src/vec_collect.rs
- src/iter/collect/mod.rs
- src/iter/extend.rs
We were using a `LinkedList<Vec<_>>` intermediary for general `ParallelExtend` implementations, gathered using a `fold` to a vector and `collect` the list -- effectively a `fold`-`fold`-`reduce`.  Now we explicitly `fold`-`map`-`reduce` it for better performance.
Thanks to @bluss for [ridiculing](https://github.com/bluss/ordermap/pull/45#discussion_r152104375) the use of `LinkedList`, which got me to look at this again.  At first I tried `Vec<Vec<_>>` instead, which did perform better, but I had to do this using `fold`-`map`-`reduce` to avoid infinite `collect` recursion.  Then I tried that same tweak on the original code, finding it slightly better yet.  So I stand by the use of `LinkedList`. :smile:
```
test map_collect::i_mod_10_to_i::with_linked_list_collect_vec_sized     ... bench: …
```
>  ParallelExtend with map-reduce 

- src/iter/mod.rs
- src/iter/test.rs
- src/iter/update.rs
- tests/clones.rs
- tests/compile-fail/must_use.rs
- tests/debug.rs
- tests/producer_split_at.rs
This resolves #487. The sequential version created by the producer is based on the `itertools` implementation. Tests are included, but let me know if you'd like better coverage.
> Add Update adaptor and `update()` method

- src/iter/from_par_iter.rs
This is more useful when combined with higher-level abstractions, like
collecting to a `Result<(), E>` where you only care about errors.
This is a parallel version of rust-lang/rust#45379.
Cc #496
> impl FromParallelIterator<()> for ()

- src/iter/extend.rs
- src/iter/from_par_iter.rs
Parallel version of rust-lang/rust#41449.
> FromParallelIterator and ParallelExtend Cow for String

- rayon-core/src/join/mod.rs
- rayon-core/src/scope/mod.rs
- rayon-core/src/thread_pool/mod.rs
Document the spawn return vaule and add doc-comments to some of the modules. Also cleanup the style of doc-comments to be a bit more consistent -- e.g., don't name the function being documented in the first sentence, which reads a bit oddly in rustdoc.
Fixes #431 
Fixes https://github.com/rayon-rs/rayon/issues/421
> document spawn return value, modules

- src/slice/mod.rs
- src/str.rs
Updates the docs for the `ParallelString` and `ParallelSlice` trait to add
examples for each method.
part of #420
> Add Examples to Documentation

- rayon-demo/src/vec_collect.rs
- src/iter/collect/consumer.rs
- src/iter/collect/mod.rs
- src/iter/mod.rs
- src/iter/plumbing/README.md
- src/iter/test.rs
- src/iter/unzip.rs
- tests/compile-fail/cannot_collect_filtermap_data.rs
- tests/compile-fail/rc_par_iter.rs
Preempts the possibility that Rust will add a collect_into method
on Iterator.
> Rename collect_into to collect_into_vec

- README.md
- rayon-core/src/join/test.rs
- rayon-core/src/lib.rs
- rayon-core/src/registry.rs
- rayon-core/src/scope/test.rs
- rayon-core/src/spawn/mod.rs
- rayon-core/src/spawn/test.rs
- rayon-core/src/test.rs
- rayon-core/src/thread_pool/mod.rs
- rayon-core/src/thread_pool/test.rs
- rayon-futures/src/test.rs
- src/iter/find_first_last/test.rs
- src/iter/test.rs
- src/lib.rs
- tests/run-pass/double_init_fail.rs
- tests/run-pass/init_zero_threads.rs
- tests/run-pass/named-threads.rs
- tests/run-pass/stack_overflow_crash.rs
Addresses #417. Still a work in progress.
Remaining questions:
Define ThreadPoolInitError. Deprecate methods that returned
Box<Error> types in favor of new methods returning the concrete
ThreadPoolInitError.
Deprecations in rayon-core:
initialize() => Configuration::init_global()
Configuration::build() => Configuration::init()
ThreadPool::new() => Configuration::init()
> Introduce concrete error type

- src/iter/mod.rs
Contribution for closing https://github.com/rayon-rs/rayon/issues/420.
There is one method left in the `ParallelIterator` trait that has no example: `opt_len`.
Also the example for `fold_with` might not be necessary.
> 420 document parallel iterator methods

- src/iter/for_each.rs
- src/iter/noop.rs
Fixes the second item of #465.
> Specialize some Folder::consume_iter methods

- src/iter/chunks.rs
- src/iter/mod.rs
- src/iter/test.rs
- src/lib.rs
- src/math.rs
- src/slice/mod.rs
- tests/clones.rs
- tests/compile-fail/must_use.rs
- tests/debug.rs
- tests/producer_split_at.rs
Fixes #501 
Note: I am only using a Vec<T> for each chunk because if I defined a Chunk iterator like itertools does, it would have to reference the type of `Producer::IntoIter` for the producer given to the ProducerCallback, which isn't accessible from the IndexedParallelIterator type. And the Chunk type needs to be the Item of the Chunks iterator.  An alternative implementation could possibly use a Box<Iterator> instead of using generics.
> Add chunks method to IndexedParallelIterator

- FAQ.md
- README.md
- rayon-core/src/join/mod.rs
- rayon-core/src/lib.rs
- rayon-core/src/scope/mod.rs
- rayon-core/src/thread_pool/mod.rs
- src/iter/mod.rs
- src/lib.rs
- src/option.rs
The iter module and join/scope functions now host the primary docs. The README and crate-level docs mostly forward to those. Some of the detailed material from the README is moved to a FAQ and lightly edited.
> revise the "overall documentation strategy"

- src/iter/mod.rs
This covers the simpler one-method traits for #420.
> Add examples to more traits

- .travis.yml
- rayon-core/src/unwind.rs
Changed from libc::abort() to std::process::abort() in unwind.rs (rayon-core) so it can be compiled for wasm32-unknown-unknown. As a consequence, both an unsafe block and the libc crate dependency for rayon-core can be removed.
Version bump in rand to 0.4, as 0.3.19 doesn't compile for wasm. It seems I'm late for the version bump (#502), so I'm not sure if I should remove it from the commit.
> Adapt for wasm32 target

- .travis.yml
- README.md
- rayon-core/Cargo.toml
- rayon-core/README.md
- rayon-core/src/lib.rs
- rayon-core/src/registry.rs
These are the changes from @stjepang and @jeehoonkang, replacing and closing #480.  The minimum rustc is *slightly* increased from 1.12 to 1.13 for the transitive requirements.
> Replace coco with crossbeam-deque

- src/slice/mod.rs
Also add an odd tail to the `par_chunks` example.
cc #420
> Add examples to par_split_mut and par_chunks_mut

- src/iter/mod.rs
- src/iter/splitter.rs
I think the split() method is a nice way to quickly build custom parallel iterators, which deserves a bit more publicity. This is an attempt at making it happen.
> Mention the split() method in the documentation of the iter module

- src/iter/splitter.rs
Rounding can falsify the previous `width < 2 * height` assertions.  For
example, given lengths `(3, 3)`, it will split to `(1, 3)` and `(2, 3)`.
cc #539 @HadrienG2
> split: use floored division in example assertion

- src/lib.rs
Browsing the Rayon 1.0 docs I hit a few snags.
> fix the relative links to the iter module

- src/slice/mod.rs
> Document how par_chunks lengths may be shorter

- .travis.yml
Using `sed` to hack rand-0.3.20 in `Cargo.lock` worked for a while, but
now it's giving us an invalid lockfile, because some of the test/demo
dependencies need rand-0.4 themselves.
Instead, we now just tweak `rayon-core/Cargo.toml` long enough to
generate a complete lock file, which is enough to get a working CI build
on Rust 1.13 again.
> Try another approach to hacking rand in CI

- FAQ.md
It's called "interior" mutability not "inherent" mutability.
Old PR of mine that already fixed this once 😄 https://github.com/rayon-rs/rayon/pull/458
Section in the book https://doc.rust-lang.org/book/second-edition/ch15-05-interior-mutability.html
> inherent mutability -> interior mutability

- Cargo.toml
- rayon-demo/src/life/bench.rs
- rayon-demo/src/life/mod.rs
- rayon-demo/src/nbody/bench.rs
- rayon-demo/src/nbody/nbody.rs
- src/iter/as_parallel.rs
- src/iter/mod.rs
- src/iter/par_bridge.rs
- src/lib.rs
- src/prelude.rs
Half of https://github.com/rayon-rs/rayon/issues/46
This started getting reviewed in https://github.com/QuietMisdreavus/polyester/pull/6, but i decided to move my work to Rayon proper.
This PR adds a new trait, `AsParallel`, an implementation on `Iterator + Send`, and an iterator adapter `IterParallel` that implements `ParallelIterator` with a similar "cache items as you go" methodology as Polyester. I introduced a new trait because `ParallelIterator` was implemented on `Range`, which is itself an `Iterator`.
The basic idea is that you would start with a quick sequential `Iterator`, call `.as_parallel()` on it, and be able to use `ParallelIterator` adapters after that point, to do more expensive processing in multiple threads.
The design of `IterParallel` is like this:
* `IterParallel` …
> add bridge from Iterator to ParallelIterator

- src/compile_fail/must_use.rs
- src/iter/fold.rs
- src/iter/mod.rs
- src/iter/try_fold.rs
- src/iter/try_reduce.rs
- src/iter/try_reduce_with.rs
- src/lib.rs
- tests/clones.rs
- tests/debug.rs
There are six variations here, matching the existing non-try suite:
- `try_fold` and `try_fold_with`
- `try_for_each` and `try_for_each_with`
- `try_reduce` and `try_reduce_with`
All of them operate on `Try::Ok` values similar to the exiting non-try
methods, and short-circuit early to return any `Try::Error` value seen.
This `Try` is a pub-in-private clone of the unstable `std::ops::Try`,
implemented for `Option<T>` and `Result<T, E>`.
TODO and open questions:
reach rust stable?  They were stabilized in rust-lang/rust#49607,
but there's always a chance this could get backed out.
- **Resolved**: they're stable in 1.27
ours private for now, and change to publicly use the standard
trait later (on sufficiently new rustc).
- **Resolved**: keep our pub-in-private `Try` for now.
globally, or …
> [WIP] Add try_fold, try_for_each, try_reduce

- src/iter/test.rs
- src/range.rs
If the length of a range of `i64`, `u64`, `i128`, or `u128` would
actually fit in `usize`, we can return that from `opt_len` to enable
some optimizations, namely indexed `collect` into vectors.  To drive
such ranges, we'll actually iterate over `(0..len)` instead, and then
map it to the larger type.
> Implement opt_len for ranges of large integers

- src/iter/mod.rs
- src/lib.rs
Hi there!
- one link was just a typo (incorrect `::*`)
- the other one was a wrong intra-link (which are still unstable)
I converted the wrong intra-link to a normal one for now. Would be awesome if this can be merged, as `cargo doc` is quite noisy on nightly when you have many dependencies :)
> Fix doc links to avoid warning on nightly

- src/iter/mod.rs
- src/iter/unzip.rs
`ParallelExtend<(A, B)>` and `ParallelExtend<Either<L, R>>` for tuples
behave like `unzip` and `partition_map` respectively.  These allow the
possibility of nested `unzip` and `partition_map` operations, filling
into more than just two collections.  For instance, `(A, (B, C))` items
can be unzipped into `(Vec<A>, (Vec<B>, Vec<C>))`.
Fixes #600.
> impl ParallelExtend for tuple pairs

- src/compile_fail/must_use.rs
- src/iter/map_with.rs
- src/iter/mod.rs
- tests/clones.rs
- tests/debug.rs
- tests/producer_split_at.rs
These are like `map_with` and all, except using an `init` function for
the paired value instead of a `Send + Clone` value.  The returned type
doesn't have to be `Send` nor `Sync` nor anything else, which makes it
feasible for things like a thread-local RNG.
> Add ParallelIterator::{map_init,for_each_init,try_for_each_init}

- src/slice/mod.rs
- tests/producer_split_at.rs
Minor change in ChunksMutProducer. `split_at` function currently panics when the last chunk is shorter than the other chunks.
> Handle the last chunk correctly

- src/iter/cloned.rs
- src/iter/filter.rs
- src/iter/filter_map.rs
- src/iter/find.rs
- src/iter/fold.rs
- src/iter/inspect.rs
- src/iter/intersperse.rs
- src/iter/map.rs
- src/iter/update.rs
- src/iter/while_some.rs
- tests/octillion.rs
This specializes the remaining "obvious" `consume_iter`s for the second part of #465. Benchmarks are included in each commit (the first specializes the types that can just defer to a `std` API, the second two require a bit more work); summary (on a 6 core/12 thread machine):
- on the included benchmarks:
- `find` is up to 1.5x faster (`find::size1::parallel_find_middle`)
- `collect` is up to 4x faster (`vec_collect::vec_i_filtered::with_collect`)
- using basic program that does something like `(0..std::u32::MAX).into_par_iter().<OPERATION>.map(test::black_box).count()`
- with no operation (i.e. just testing `map`/`count`): 8x faster
- with `.map(Some).while_some()`: 3x faster
- with `.intersperse(1)`: 10x faster
The remaining types without a specialization are:
```
$ rg …
```
> Specialize more `consume_iter`s

- rayon-core/src/registry.rs
- tests/sort-panic-safe.rs
Nightly 1.34 suggests the const `AtomicUsize::new()` instead, but we
still want to support older compilers, so just allow it for now.
> Allow the deprecated ATOMIC_USIZE_INIT

- src/iter/mod.rs
- src/iter/plumbing/README.md
- src/iter/test.rs
PR opened in response to #607.
> Add `find_map` with `any`, `first`, and `last` variants

- rayon-core/src/lib.rs
Using `#[derive(Default)]` started triggering `Configuration`'s own
deprecation message on nightly, as it has been on our compat 1.13 as
well (though stable has been fine). We can easily `#[allow(deprecated)]`
on a manual `impl` to avoid this.
> #[allow(deprecated)] impl Default for Configuration

- Cargo.toml
I'm trying to make my crates work with `cargo -Z minimal-versions` to ensure that versions specified in my Cargo.toml are actual versions that work with my crate.
The problem is, it's not true for Rayon's dependencies: rayon 1.0.3 uses rayon-core 1.4.0, which uses rand 0.3.12, which uses advapi32-sys 0.1.2, which uses winapi 0.0.1, which isn't compatible with Rust 1.0.
The problem has been fixed in rayon-core 1.4.1, so that should be the minimal version used by rayon.
> Require rayon-core ^1.4.1

- src/compile_fail/must_use.rs
- src/iter/collect/consumer.rs
- src/iter/collect/test.rs
- src/iter/mod.rs
- src/iter/panic_fuse.rs
- tests/clones.rs
- tests/debug.rs
- tests/iter_panic.rs
- tests/producer_split_at.rs
This wraps an iterator with a fuse in case of panics, to halt all
threads as soon as possible. While we always propagate panics anyway,
that doesn't usually synchronize across threads, so iterators may end up
processing many more items before the panic is realized. With
`panic_fuse()`, a shared `AtomicBool` is checked before processing each
item, and set for any panic unwinding in its path.
> Add ParallelIterator::panic_fuse()

- src/lib.rs
- src/range_inclusive.rs
- tests/clones.rs
- tests/debug.rs
- tests/octillion.rs
- tests/producer_split_at.rs
All the grunt work is forwarded to `range::Iter`, with fixups for the
end case as needed.
Fixes #572.
> impl ParallelIterator for RangeInclusive

- README.md
> docs: fix "double wording"

- rayon-core/Cargo.toml
- rayon-core/src/lib.rs
- rayon-core/src/private.rs
- rayon-core/src/registry.rs
- rayon-core/src/test.rs
- rayon-core/src/thread_pool/mod.rs
- rayon-core/tests/scoped_threadpool.rs
- src/lib.rs
As an alternative to `ThreadPoolBuilder::build()` and `build_global()`,
the new `spawn()` and `spawn_global()` methods take a closure which will
be responsible for spawning the actual threads. This is called with a
`ThreadBuilder` argument that provides the thread index, name, and stack
size, with the expectation to call its `run()` method in the new thread.
The motivating use cases for this are:
- experimental WASM threading, to be externally implemented.
- scoped threads, like the new test using `scoped_tls`.
> Add the ability to customize thread spawning

- .gitignore
- rayon-core/src/job.rs
- rayon-core/src/join/mod.rs
- rayon-core/src/latch.rs
- rayon-core/src/registry.rs
This addresses the first half of #666.
I kept the `LockLatch` and added a `reset()` method because that had overall fewer lines of code. If you want I can still change it to a separate `ReusableLockLatch` type.
> Reusing LockLatch to reduce allocation 

- .travis.yml
- Cargo.toml
- README.md
- rayon-core/Cargo.toml
- rayon-core/README.md
- rayon-core/src/lib.rs
- rayon-core/src/registry.rs
- src/iter/par_bridge.rs
- src/lib.rs
The only substantive change is to 'take_local_job'.
'Worker::pop` now returns a plain 'Option<T>', so there's
no need to loop anymore
> Update crossbeam-deque to 0.7

- rayon-core/src/job.rs
- rayon-core/src/join/mod.rs
- src/iter/collect/mod.rs
- src/iter/copied.rs
- src/iter/extend.rs
- src/iter/find.rs
- src/iter/flatten.rs
- src/iter/fold.rs
- src/iter/for_each.rs
- src/iter/from_par_iter.rs
- src/iter/interleave.rs
- src/iter/map_with.rs
- src/iter/mod.rs
- src/iter/noop.rs
- src/iter/panic_fuse.rs
- src/iter/skip.rs
- src/iter/try_fold.rs
- src/iter/try_reduce.rs
- src/iter/update.rs
- src/iter/while_some.rs
- src/option.rs
- src/range.rs
- src/result.rs
- src/slice/mod.rs
- src/split_producer.rs
- src/str.rs
- tests/issue671-unzip.rs
- tests/issue671.rs
The `take_while` closure only needs to be generic in `T`, along with a
captured `&AtomicBool`. When we write the closure directly, it carries
all the type baggage of `WhileSomeFolder<'f, C>::consumer_iter<I>`,
where the monomorphized type may explode. Instead, we can move this
closure to a standalone function for reduced genericity.
> Reduce the genericity of many closures

- src/lib.rs
As they contain the often looked up methods, have them readily
available.
Closes #687.
> Link the iterator traits from top of the docs

- src/iter/mod.rs
Because I spent quite a while yesterday and today tracking this problem down, I thought it might be an improvement to the documentation to mention that Rayon's ParallelIterator and friends are not object-safe (and why).
(c.f. #628)
> Adds info about (lack of) object safety to `iter` module documentation.

- rayon-core/Cargo.toml
Just did a `cargo update` on my project today morning and noticed that with the release of **crossbeam-epoch 0.8.0**, rayon starts to depend on 2 versions of **crossbeam-utils**.
Before:
```
rayon-core v1.6.0
├── crossbeam-deque v0.7.2
│   ├── crossbeam-epoch v0.8.0
│   │   └── crossbeam-utils v0.7.0 <-- latest
│   └── crossbeam-utils v0.7.0     <-- latest
├── crossbeam-queue v0.1.2
│   └── crossbeam-utils v0.6.6     <-- outdated
└── crossbeam-utils v0.6.6         <-- outdated
```
Here Rust will compile 2 versions of the same dependency.
After:
```
rayon-core v1.6.0
├── crossbeam-deque v0.7.2
│   ├── crossbeam-epoch v0.8.0
│   │   └── crossbeam-utils v0.7.0 <-- latest
│   └── crossbeam-utils v0.7.0     <-- latest
├── crossbeam-queue v0.2.0
│   └── crossbeam-utils v0.7.0     <-- latest
└── …
```
> Update crossbeam to avoid multi version dependency

- appveyor.yml
CI for #711 ran into a broken beta windows-gnu toolchain, which is frustrating, but in general I already feel that it's overkill to test so much on Windows. The Linux builds on Travis CI already test a breadth of compiler versions, and it does so in parallel, whereas Appveyor runs serially. We can just test Windows stable to be sure the platform works at all, and leave it at that.
> Reduce Windows CI to just stable Rust

- src/iter/mod.rs
- src/iter/multizip.rs
- tests/clones.rs
- tests/debug.rs
This is implemented for tuples up to arity 12, much like the standard
library's trait implementations.
- For `(a, b, ...)`, it calls `into_par_iter()` on each member.
- For `&(a, b, ...)`, it calls `par_iter()` on each member.
- For `&mut (a, b, ...)`, it calls `par_iter_mut()` on each member.
The resulting `MultiZip` iterator returns a tuple of the zipped items
from each input iterator. Internally, it is implemented with macros that
forward to a series of regular `zip`s, mapping to a flattened tuple.
Closes #567.
> impl IntoParallelIterator for tuples => MultiZip

- .travis.yml
- RELEASES.md
- appveyor.yml
- ci/compat-Cargo.lock
- rayon-futures/Cargo.toml
- rayon-futures/README.md
- rayon-futures/src/compile_fail/mod.rs
- rayon-futures/src/compile_fail/non_send_item.rs
- rayon-futures/src/lib.rs
This includes the soundness fix from #698, just targeted to a new branch.
> Release and deprecate rayon-futures 0.1.1

- src/iter/plumbing/mod.rs
This patch changes the wording of the documentation, because right now it is "There's a highlevel overview over the low level stuff", which is ridiculous.
Rather use "general overview" for less funny wording.
> Change wording, less "High level for low level"

- src/slice/mod.rs
- src/slice/test.rs
- tests/clones.rs
- tests/debug.rs
- tests/producer_split_at.rs
Follow-up PR from #510. `chunks_exact` (and its mutable counterpart) are not yet implemented on `ParallelIterator`, only `ParallelSlice`.
> Implement chunks_exact and chunks_exact_mut

- Cargo.toml
- ci/compat-Cargo.lock
- rayon-demo/Cargo.toml
- rayon-demo/src/lib.rs
- src/lib.rs
We've used `doc_comment::doctest!` to push the README through rustdoc
testing, but its `#[cfg(doctest)]` only works on 1.40+, and causes a
hard error on 1.38 and 1.39. Now we move this into rayon-demo so it
doesn't hurt compatibility of the main library.
> Move doctest to the rayon-demo library

- src/iter/mod.rs
All variants return `first_number` and `find_map_any` is not used 😝
> Fix wrong examples of find_map variants

- rayon-core/src/latch.rs
- rayon-core/src/registry.rs
- tests/cross-pool.rs
`TickleLatch` is used for synchronizing between multiple thread pools.
It sets an internal latch, and then tries to tickle the remote pool to
notice the completion. However, if the other pool is already awake and
sees the set flag, it may continue and drop the whole job, invalidating
further reads from the latch.
We can fix this by reading all fields from the `&self` latch _before_
calling the internal `set()`. Furthermore, I've updated this to take a
full `Arc<Registry>` handle, so we're also sure that the other pool
won't be destroyed too soon.
The new `tests/cross-pool.rs` would usually still pass before, but the
race could be increased by adding a manual `yield_now()` between the
`set()` and `tickle()`. This PR still passes under that same hack.
Fixes #739.
> Fix TickleLatch reading stale data after set()

- src/iter/mod.rs
I couldn't find `collect_into_vec` until I noticed that it's not in `ParallelIterator`, but in `IndexedParallelIterator`.
> Note that collect_into_vec is in a different trait

- build.rs
- src/range.rs
- src/range_inclusive.rs
- tests/chars.rs
Closes #770
Implements both unindexed and indexed parallel iteration for `Range<char>` and `RangeInclusive<char>`.
> impl IntoParallelIterator for Range<char>

- ci/compat-Cargo.lock
- rayon-core/Cargo.toml
- rayon-core/src/join/mod.rs
- rayon-core/src/latch.rs
- rayon-core/src/log.rs
- rayon-core/src/registry.rs
- rayon-core/src/scope/mod.rs
- rayon-core/src/sleep/README.md
- rayon-core/src/sleep/counters.rs
- rayon-core/src/sleep/mod.rs
- rayon-demo/src/life/mod.rs
Implementation of the scheduler described in https://github.com/rayon-rs/rfcs/pull/5 -- modulo the fact that the RFC is mildly out of date. There is a [walkthrough video available](https://youtu.be/HvmQsE5M4cY).
To Do List:
> new scheduler from RFC 5

- rayon-core/src/spawn/mod.rs
`spawn_future()` doesn't exist anymore, so this commit removed a reference to it from the documentation. This closes https://github.com/rayon-rs/rayon/issues/234
> Removed outdated documentation

- ci/compat-Cargo.lock
- rayon-core/Cargo.toml
- rayon-core/src/job.rs
- rayon-core/src/registry.rs
`Injector` and `SegQueue` are _almost_ identical, down to the very same
comments in their implementations. One difference is that `Injector`
allocates its first block as soon as it's created, but `SegQueue` waits
until its first `push`, which complicates it to allow being `null`.
`Injector` also has methods to steal batches into a deque `Worker`,
which might be useful to us.
At the very least, this lets us trim a dependency.
> Use crossbeam_deque::Injector instead of crossbeam_queue::SegQueue

- rayon-core/src/registry.rs
This lifts up the loop for `Steal::Retry`, so we continue with other
threads before trying again. For most benchmarks, the performance change
is in the noise, but this gives a consistent improvement in most of the
microbenches -- up to 8% faster on `join_microbench::increment_all_max`.
> Micro-optimize the WorkerThread::steal loop

- rayon-core/src/scope/mod.rs
- rayon-core/src/scope/test.rs
- rayon-core/src/thread_pool/mod.rs
- rayon-core/src/thread_pool/test.rs
We already know the `OP` lifetime must outlive the `scope` call itself,
and we'll execute it synchronously, but we don't need to tie that to the
`'scope` lifetime. By relaxing this, we can create scopes for different
lifetimes than `OP` can satisfy, even fully `'static`. They will still
await completion by the end of the `scope` call, but this can be useful
for collecting the invariant scopes from different contexts, as the new
nested tests demonstrate (adapted from @pkolaczk's code in #782).
> Remove the lifetime constraint from the scope OP

- Cargo.toml
- RELEASES.md
- ci/compat-Cargo.lock
- rayon-core/Cargo.toml
- rayon-core/src/lib.rs
- src/lib.rs
- Implemented a new thread scheduler, [RFC 5], which uses targeted wakeups for
new work and for notifications of completed stolen work, reducing wasteful
CPU usage in idle threads.
- Implemented `IntoParallelIterator for Range<char>` and `RangeInclusive<char>`
with the same iteration semantics as Rust 1.45.
- Relaxed the lifetime requirements of the initial `scope` closure.
[RFC 5]: https://github.com/rayon-rs/rfcs/pull/5
> Release rayon 1.4.0 / rayon-core 1.8.0

- src/collections/binary_heap.rs
- src/collections/hash_map.rs
- src/collections/hash_set.rs
- src/collections/mod.rs
- src/collections/vec_deque.rs
- src/iter/mod.rs
- src/lib.rs
- src/math.rs
- src/prelude.rs
- src/string.rs
- src/vec.rs
- tests/debug.rs
These define methods of the same name, so only one is expected to be
implemented for any given collection type. Collections that support
ranges can always call `par_drain(..)` for a full drain.
```rust
pub trait ParallelDrainRange<Idx = usize> {
type Iter: ParallelIterator<Item = Self::Item>;
type Item: Send;
fn par_drain<R: RangeBounds<Idx>>(self, range: R) -> Self::Iter;
}
pub trait ParallelDrainFull {
type Iter: ParallelIterator<Item = Self::Item>;
type Item: Send;
fn par_drain(self) -> Self::Iter;
}
```
> Add traits ParallelDrainRange and ParallelDrainFull

- .github/workflows/ci.yaml
- Cargo.toml
- RELEASES.md
- bors.toml
- ci/compat-Cargo.lock
- rayon-core/Cargo.toml
- rayon-core/src/join/test.rs
- rayon-core/src/sleep/counters.rs
- tests/octillion.rs
32-bit targets only have 12 bits in the atomic counters to represent the Jobs Event Counter (JEC). This should be fine with wrapping addition, but commit a0efb4a changed from wrapping `fetch_add` to a plain `+`, which is a checked addition in debug builds. We simply need to make this an explicit `wrapping_add` instead.
In theory, 64-bit targets had a problem too, but 44 bits for JEC is pretty good headroom in debug mode.
Fixes #797.
> Use wrapping addition for JEC

- src/compile_fail/must_use.rs
- src/iter/flat_map.rs
- src/iter/flat_map_iter.rs
- src/iter/flatten.rs
- src/iter/flatten_iter.rs
- src/iter/mod.rs
- tests/clones.rs
- tests/debug.rs
The existing `flat_map` and `flatten` adaptors expect items that
implement `IntoParallelIterator`, and they each go through a new round
of parallel task splitting. This often creates smaller task granularity
than people intended, especially if they're doing something simple on
the flattened iterator like `collect()` or `sum()`.
The new `flat_map_iter` and `flatten_iter` expect `IntoIterator` items,
which are simply flattened directly within the current parallel task.
The iterator doesn't even need to be thread safe, because it never
leaves the thread where it is created, only its items.
> Add flat_map_iter and flatten_iter

- src/compile_fail/must_use.rs
- src/iter/mod.rs
- src/iter/positions.rs
- tests/clones.rs
- tests/debug.rs
This is the plural of the `position` methods, where `positions` finds
_all_ matching items and returns their indices in a new iterator. This
matches the API of `Itertools::positions`, but in parallel.
> Add a parallel iterator of matching positions

- .github/workflows/ci.yaml
- .github/workflows/pr.yaml
- Cargo.toml
- README.md
- bors.toml
- ci/compat-Cargo.lock
- rayon-core/Cargo.toml
- src/iter/copied.rs
Update to the latest versions of:
* crossbeam-channel (0.5.0)
* crossbeam-deque (0.8.0)
* crossbeam-utils (0.8.0)
This increases the minimum Rust toolchain requirement from 1.31 to 1.36.
> Update crossbeam dependencies (requires Rust 1.36)

- src/iter/mod.rs
The doc links in the iter module appears broken on docs.rs:
https://docs.rs/rayon/1.5.0/rayon/iter/trait.IndexedParallelIterator.html?search=#tymethod.with_producer
This PR updates the links to point to the correct location.
> Fix broken doc links in iter module

- src/range.rs
- src/range_inclusive.rs
Fixes #833 type inference by adding traits that are used as a constraint
directly on integer types for ranges and their `Iter` implementations,
rather than implementing each `Iter<{integer}>` separately. The traits
have to be `pub` since they're used by public `impl<T> ... for Iter<T>`,
but they're hidden in a private module to stay out of our semver API.
> Add a pub-in-private trait for Range integers

- src/iter/mod.rs
- src/iter/unzip.rs
Like #604 for `ParallelExtend`, implementing `FromParallelIterator` for tuple pairs opens up new possibilities for nesting `collect`. The possibility of short-circuiting into `Result<(T, U), E>` for #801 is particularly motivating.
- `FromParallelIterator<(A, B)> for (FromA, FromB)` works like `unzip`
- `FromParallelIterator<Either<L, R>> for (A, B)` works like `partition_map`
> impl FromParallelIterator for tuple pairs

- README.md
This is probably more useful than just showing the badge and matches the behavior of the previous CI badges.
> Link to GitHub Actions page

- src/iter/par_bridge.rs
We have the `done` flag to indicate when the bridged iterator is out of
items, but there may still be items left in the parallel deque as well!
Threads should check both, in that order, otherwise they may drop out of
the bridge party while there's still work to do.
Fixes #848.
> Make sure `ParBridge` threads consume all items after `done`

- src/iter/collect/consumer.rs
- src/iter/collect/mod.rs
- src/iter/collect/test.rs
- src/vec.rs
We create a mutable slice to the uninitialized tail when collecting into
a `Vec<T>`, but the Rust Reference says it's UB to produce "a reference
or `Box<T>` that is dangling, unaligned, or points to an invalid value."
[UCG#77] hasn't resolved the validity of references to uninitialized
data yet, but we can avoid it by using `MaybeUninit<T>`.
[UCG#77]: https://github.com/rust-lang/unsafe-code-guidelines/issues/77
Fixes #851.
> Use `&mut [MaybeUninit<T>]` in `iter::collect`

- rayon-core/src/latch.rs
- rayon-core/src/lib.rs
- rayon-core/src/registry.rs
- rayon-core/src/scope/mod.rs
- rayon-core/src/thread_pool/mod.rs
- rayon-core/src/thread_pool/test.rs
- src/lib.rs
> Implement `in_place_scope`

- rayon-core/src/lib.rs
- rayon-core/src/scope/mod.rs
- rayon-core/src/thread_pool/mod.rs
- rayon-core/src/thread_pool/test.rs
- src/lib.rs
This matches the recent `in_place_scope`, but using `ScopeFifo`. The
scope constructors have also been refactored to avoid duplication.
> Add `in_place_scope_fifo`

- src/iter/skip.rs
`Skip` still executes the skipped part of the iterator with a no-op
consumer in case there are side effects, as a point of compatibility
with sequential `Skip`. However, the `Producer` is not necessarily
`'static`, and `ProducerCallback::Output` doesn't require `Send`, so we
didn't have a way to run the no-op in parallel with the normal callback.
Now with `in_place_scope`, we can `spawn` the no-op consumer while we
run the callback directly. The scope will still wait for that no-op to
complete before returning, propagating panics if necessary.
> Use in_place_scope to spawn skipped items

- src/slice/chunks.rs
- src/slice/mod.rs
- src/slice/rchunks.rs
- src/slice/test.rs
- tests/clones.rs
- tests/debug.rs
- tests/producer_split_at.rs
These additions work mostly like `par_chunks*` in reverse, but aligned against the end of the slice if the length is not a perfect multiple of the chunk size. The `Exact` variants also have remainder methods matching their forward counterparts.
```rust
pub trait ParallelSlice<T> {
fn par_rchunks(&self, chunk_size: usize) -> RChunks<'_, T>;
fn par_rchunks_exact(&self, chunk_size: usize) -> RChunksExact<'_, T>;
}
pub trait ParallelSliceMut<T> {
fn par_rchunks_mut(&mut self, chunk_size: usize) -> RChunksMut<'_, T>;
fn par_rchunks_exact_mut(&mut self, chunk_size: usize) -> RChunksExactMut<'_, T>;
}
```
Fixes #734.
> Add `par_rchunks*` for slices

- Cargo.toml
- ci/compat-Cargo.lock
- rayon-core/Cargo.toml
- rayon-demo/Cargo.toml
Updates crossbeam and glium for cargo audit purposes. crossbeam had security vulnerability in 0.8.0 so am giving some range availability in which version to pick, ideally this makes updates like this pr needed less frequently
> Update dependencies for cargo audit

- build.rs
- src/array.rs
- src/iter/mod.rs
- src/iter/step_by.rs
- src/iter/try_fold.rs
- src/iter/try_reduce.rs
- src/iter/try_reduce_with.rs
While `std::ops::Try` is still unstable, we can privately mirror recent changes to our own copy. Rust 1.55 _is_ stabilizing `enum ControlFlow` though, which also implements `Try` for the stable `?`-operator and `Iterator::try_*`, so we can support that as well. Finally, `std::task::Poll` was stabilized in 1.36, with `Try` implementations for `Poll<Result<T, E>>` and `Poll<Option<Result<T, E>>>`, so again we can mimic that.
> Update to try_trait_v2 and stable ControlFlow

- README.md
I wasn't sure at first if you'd be interested in linking to the adapter from Rayon docs, but seeing more and more projects using this integration already, figured it might be useful.
Feel free to close if you think otherwise.
> Add mini-section on Wasm usage

- src/iter/mod.rs
Because it depends on scheduling and job size how many jobs are
processed per thread, it seems more consistent to say rayon job here.
> Use the wording 'rayon job' for with_min/max_len

- src/iter/collect/mod.rs
- src/iter/extend.rs
For unindexed parallel itererators, we've implemented `ParallelExtend`
for most collections using an intermediate `LinkedList<Vec<T>>` like:
```rust
par_iter
.into_par_iter()
.fold(Vec::new, vec_push)
.map(as_list)
.reduce(LinkedList::new, list_append)
```
However, this introduces `Fold`, `Map`, and `Reduce` types that are all
dependent on the input iterator type. When it comes to very complicated
cases like nested tuple unzips, this can add up quickly. For example, in
rust-lang/rust#68926 an 8-way unzip leads to 3.7GB of LLVM IR, with
lines up to 67K characters in long generic types.
Now we add a new `ListVecConsumer` that is not generic at all itself,
and implements `Consumer<T>` etc. generic only on the item type. So each
collection now gets the same `LinkedList<Vec<T>>` as before …
> Reduce the amount of generic code for ParallelExtend

- rayon-demo/src/str_split.rs
- src/str.rs
- tests/str.rs
The standard library has had this since 1.0, so I don't know why we didn't add it here.
> impl Pattern for &[char]

- src/iter/collect/consumer.rs
- src/iter/collect/mod.rs
- src/iter/collect/test.rs
- src/lib.rs
- src/slice/mergesort.rs
- src/slice/quicksort.rs
- src/vec.rs
I've submitted a few PRs to other libraries to address errors from running `cargo miri test` on them. Not all of the code that Miri rejects as not conforming to Stacked Borrows is necessarily invalid in terms of current rustc+LLVM semantics, but some of it is a little dubious on its own, and also I think it would be really nice for core libraries to be clean against miri so that we can use miri to understand how well people follow the prototype rules without Miri being halted by non-conforming code in dependencies.
To that end, I'm here because I was running `cargo miri test --features=rayon` in the `hashbrown` crate, and I got an error that I could trace back to this crate. Then I started running `cargo miri test` with `MIRIFLAGS="-Zmiri-disable-isolation -Zmiri-tag-raw-pointers"` on …
> Address SB/provenance issues found by cargo miri test

- rayon-core/src/lib.rs
- rayon-core/src/registry.rs
- rayon-core/src/sleep/counters.rs
- rayon-core/src/sleep/mod.rs
- src/lib.rs
We have an inherent maximum on the number of threads we can support in a
single thread pool, based on the number of `THREADS_BITS` we are using
in the atomic sleep counters. However, we were not enforcing this, so a
larger pool could be created and end up wrapping the counters. In debug
builds this would fail an assertion, otherwise it may lead to errors in
the desired sleep and wakeup behavior.
We now assert this limit in `Sleep::new`, and also impose it as a soft
limit in `Registry::new`, automatically reducing to the maximum. A
top-level `pub fn max_num_threads()` returns the maximum for users.
At the same time, the value of `THREADS_BITS` is now adjusted for
different machine sizes. It was 10 bits everywhere, but 32-bit systems
now use 8 bits for max 255 threads (leaving more room for …
> Enforce THREADS_MAX and expose it with max_num_threads()

- src/delegate.rs
The documented example wasn't functional, and this broke on nightly since rust-lang/rust#96630.
We can't actually doctest a nonexported macro, but a unit test will do.
> Convert delegate doctest to unit tests

- build.rs
If rayon is built in a configuration with warnings as error (e.g., `RUSTFLAGS=-Dwarnings`), then the probe will fail even though the compiler does have the necessary const generic support.
> Rename autocfg probe method to _foo to avoid dead code warning

- RELEASES.md
- ci/compat-Cargo.lock
- rayon-core/Cargo.toml
- rayon-core/src/latch.rs
- rayon-core/src/registry.rs
- rayon-core/src/spawn/mod.rs
- rayon-core/src/test.rs
- rayon-core/src/thread_pool/test.rs
`SpinLatch<'r>` borrows `&'r Arc<Registry>` from the `WorkerThread` where it is created. When we `set`, we're careful to make sure that the `Registry` remains alive while we do the inner `set` and then `notify_worker_latch_is_set`. We knew from past bugs that the `SpinLatch` could be invalidated between set and notify, but the `&Arc` could also be invalidated if the target thread sees the set *and exits* (dropping its `WorkerThread`) before the notification. That's a fairly long race, but preemption could make that happen.
The inner `Registry` will still be alive, since the current thread is part of that pool, so we can hold that reference directly.
Fixes #913
Fixes #929
> Fix a use-after-free race in SpinLatch::set, and release 1.9.3

- rayon-demo/src/sort.rs
- src/slice/mod.rs
This is a port of the standard library's `slice::sort_by_cached_key` as `ParallelSliceMut::par_sort_by_cached_key`. We can do the initial key-caching indexed `collect` in parallel, and then use `par_sort_unstable` on that, but the final rearrangement on the original slice is still sequential.
The new benchmarks test integers with a `to_string` key, and it looks great on my Ryzen 7 5800X:
```
test sort::par_sort_by_cached_key   ... bench:   3,464,639 ns/iter (+/- 253,378) = 115 MB/s
test sort::par_sort_by_key          ... bench:   6,865,096 ns/iter (+/- 204,145) = 58 MB/s
test sort::par_sort_unstable_by_key ... bench:  13,346,235 ns/iter (+/- 1,966,048) = 29 MB/s
```
While I was in the neighborhood, I also updated documentation changes in the other sorting methods that were ported from the …
> Add par_sort_by_cached_key

- rayon-core/src/job.rs
- rayon-core/src/scope/mod.rs
- rayon-core/src/spawn/mod.rs
Where `JobRef` was transmuting the `execute` function pointer to hide
its argument type, we can instead pass the opaque `*const ()` and let
the callee cast the pointer type.
Where `HeapJob` was transmuting its own `Box<Self>`, we can instead use
`Box::into_raw` and `Box::from_raw`. It can also call its function right
out of the recovered `Box`.
> Remove `mem::transmute` calls from job handling

- rayon-core/src/latch.rs
- rayon-core/src/registry.rs
- rayon-core/src/scope/mod.rs
This reverts commit 1dfd5d90e562b2aac0673b1cb611eafdd783701d.
This was a mistake -- multiple threads can't wait on the same latch,
because the inner `CoreLatch` tracks thread-specific sleep state.
> Revert "Use a single termination latch for the registry"

- src/slice/quicksort.rs
https://github.com/rust-lang/rust/pull/93765 shows
a 10% speedup and had been merged into std.
Given that rayon's code was an exact copy of the
heapsort in std, this PR implements the same
optimization.
> Keep heapsorts implementation equal to std

- rayon-core/src/lib.rs
We only run tests on stable Rust, so this adds a doctest with the new `std::thread::scope`.
See also #948 to use that internally, but that will increase the crate MSRV.
> Document an example with `std::thread::scope`

- .github/workflows/ci.yaml
- .github/workflows/pr.yaml
- README.md
- bors.toml
- rayon-core/README.md
- src/iter/mod.rs
- src/slice/mod.rs
`#[track_caller]` makes assert location point to the caller of the function. This helps users find which of their calls provided the invalid inputs.
> Attribute invalid input assertions to callers

- README.md
Right now it says: 
_"Opening a pull requests is assumed to signal agreement with these licensing terms."_ 
It should probably instead say one of the two below:
- _"Opening a pull REQUEST is assumed to signal agreement with these licensing terms."_
- _"The opening of pull requests is assumed to signal agreement with these licensing terms."_
> Fix tiny typo in licensing section of readme

- rayon-demo/src/factorial/mod.rs
- src/compile_fail/must_use.rs
- src/iter/fold_chunks.rs
- src/iter/fold_chunks_with.rs
- src/iter/mod.rs
- tests/clones.rs
- tests/debug.rs
This adds two iterators to allow working with fixed-size chunks in a similar way to `chunks()` but without incurring the overhead of allocating a `Vec<T>` for each chunk.
Something similar was discussed in #773.
A call such as:
```
par_iter.fold_chunks(chunk_len, || init(), |acc, x| foo(acc, x))
```
would be functionally equivalent to:
```
par_iter.chunks(chunk_len)
.map(|chunk|
chunk.into_iter()
.fold(init(), |acc, x| foo(acc, x|))
```
A final `fold()` (or `for_each()`, `sum()`, etc) across all mapped chunks can be chained by user code if needed, like this I think it's more flexible.
> add fold_chunks and fold_chunks_with parallel iterators

- RELEASES.md
- ci/compat-Cargo.lock
- rayon-core/Cargo.toml
- rayon-core/src/broadcast/test.rs
- rayon-core/src/registry.rs
The sleep code checks `has_injected_jobs` as the final step before
blocking the thread, but this was only looking at the normal pool-
injected jobs. With `broadcast`, there's now a way to inject jobs
directly on each thread, which they should also check individually
before going to sleep -- and now they do!
> Fix a sleep race with broadcast jobs

- src/iter/par_bridge.rs
Fix issue #795
instead of using crossbeam_deque, just lock the Iterator and get the next item, naively. The original code would spin until more data became available, which would cause par_bridge to not be useful in cases where the source Iterator did slow IO or was computationally costly in itself.
This causes there to be virtually no change in runtime in many cases, but in cases where there are a lot CPUs and even slightly slower IO, significantly less runtime.
In pretty much every case, total CPU time was much lower.
I ran the below test program on a 1.5GiB file from a fast SSD and on a machine with 64 cores and mean runtime went from 44s to 30s. In fact, according to hyperfine, average runtime with this patch was lower than _minimum_ runtime without (25s and 41s, respectively). But …
> par_bridge: use naive locking of the Iterator

- Cargo.toml
- RELEASES.md
- ci/compat-Cargo.lock
- src/iter/par_bridge.rs
- tests/par_bridge_recursion.rs
It doesn't make sense for the `par_bridge` producer to run nested on one
thread, since each split is capable of running the entire iterator to
completion. However, this can still happen if the serial iterator or the
consumer side make any rayon calls that would block, where it may go
into work-stealing and start another split of the `par_bridge`. With the
iterator in particular, this is a problem because we'll already be
holding the mutex, so trying to lock again will deadlock or panic.
We now set a flag in each thread when they start working on the bridge,
and bail out if we re-enter that bridge again on the same thread. The
new `par_bridge_recursion` test would previously hang almost every time
for me, but runs reliably with this new check in place.
> Guard `par_bridge` against work-stealing recursion

- rayon-core/Cargo.toml
- rayon-core/tests/stack_overflow_crash.rs
- Rewrite it within the regular test harness, so it doesn't crash in
arg-parsing on broad `cargo test -- filter` commands.
- Use `std::hint::black_box` so the test even works in `--release`.
> Improve rayon-core/tests/stack_overflow_crash.rs

- rayon-core/src/broadcast/mod.rs
- rayon-core/src/job.rs
- rayon-core/src/latch.rs
- rayon-core/src/registry.rs
- rayon-core/src/scope/mod.rs
`Latch::set` can invalidate its own `&self`, because it releases the
owning thread to continue execution, which may then invalidate the latch
by deallocation, reuse, etc. We've known about this problem when it
comes to accessing latch fields too late, but the possibly dangling
reference was still a problem, like rust-lang/rust#55005.
The result of that was rust-lang/rust#98017, omitting the LLVM attribute
`dereferenceable` on references to `!Freeze` types -- those containing
`UnsafeCell`. However, miri's Stacked Borrows implementation is finer-
grained than that, only relaxing for the cell itself in the `!Freeze`
type. For rayon, that solves the dangling reference in atomic calls, but
remains a problem for other fields of a `Latch`.
This easiest fix for rayon is to use a raw pointer …
> Use pointers instead of `&self` in `Latch::set`

- .github/workflows/ci.yaml
- rayon-core/src/broadcast/test.rs
- rayon-core/src/join/test.rs
- rayon-core/src/lib.rs
- rayon-core/src/registry.rs
- rayon-core/src/scope/test.rs
- rayon-core/src/spawn/test.rs
- rayon-core/src/test.rs
- rayon-core/src/thread_pool/test.rs
- rayon-core/tests/double_init_fail.rs
- rayon-core/tests/init_zero_threads.rs
- rayon-core/tests/scoped_threadpool.rs
- rayon-core/tests/stack_overflow_crash.rs
- src/iter/collect/test.rs
- src/iter/test.rs
- src/lib.rs
- tests/collect.rs
- tests/cross-pool.rs
- tests/iter_panic.rs
- tests/named-threads.rs
- tests/octillion.rs
- tests/par_bridge_recursion.rs
- tests/sort-panic-safe.rs
> Add a fallback when threading is unsupported

- src/iter/mod.rs
- src/iter/skip_any.rs
- src/iter/take_any.rs
The existing `take` and `skip` are only part of `IndexedParallelIterator`, while these new adaptors will take/skip from anywhere in a `ParallelIterator`.
This PR extends the documentation from #1012.
> Add TakeAny and SkipAny

- src/iter/mod.rs
- src/iter/skip_any_while.rs
- src/iter/take_any_while.rs
- tests/clones.rs
- tests/debug.rs
These are like `Iterator::take_while` and `skip_while`, but the `any`
names emphasize that they're not a straightforward parallelization, as
they does not honor the original iterator order.
> Add `ParallelIterator::take_any_while` and `skip_any_while`

- rayon-core/src/job.rs
- rayon-core/src/join/mod.rs
- rayon-core/src/registry.rs
- rayon-core/src/scope/mod.rs
- rayon-core/src/spawn/mod.rs
I don't see any difference in benchmarks from this, and only a slight reduction in code size. If nothing else I think it's more principled that `JobRef` should not implement `Copy` in particular. `Registry::inject` taking a slice of jobs was an over-abstraction that we never used.
> Stop deriving traits on JobRef

- src/array.rs
- src/vec.rs
This makes a greater effort to ensure that in all cases where either
`DrainProducer` or `SliceDrain` will drop data, there are no references
left pointing to that memory. It's not actually clear that this would be
a problem anyway, as long as there's nothing accessing that zombie data,
but it's not too much trouble to avoid it.
Fixes #1029.
> Be more cautious about drain drops

- rayon-core/src/lib.rs
- rayon-core/src/registry.rs
- rayon-core/src/thread_pool/mod.rs
- rayon-core/src/thread_pool/test.rs
- src/lib.rs
* `yield_now` looks for work anywhere in the thread pool and executes it.
* `yield_local` only looks in the thread-local deque (including broadcasts).
In either case, they return:
* `Some(Yield::Executed)` if work was found and executed.
* `Some(Yield::Idle)` if no work was found in their pool/thread.
* `None` if the current thread is not part of a thread pool.
These do not call `std::thread::yield_now()`, but the docs suggest polling loops might want to add that as a fallback.
> Add `yield_now` and `yield_local`

- src/slice/quicksort.rs
There is a struct with a destructor borrowing from a local, it would be good to have some lifetimes protecting it from doing the wrong thing.
mergesort.rs also has this type but it's constructing it from raw pointers and I didn't want to infect everything with lifetimes. It's less of a problem there since it's *not* borrowing from locals.
> Use phantomdata in CopyOnDrop

- src/iter/mod.rs
"cleared" is more precise than "truncated" as Rust's truncate may be partial
> clarify collect/unzip_into_vec

- .github/workflows/ci.yaml
- .github/workflows/master.yaml
- .github/workflows/pr.yaml
This reverts commit ed42b2926f0317056aa65ce802964191e37fe5f5.
The sparse protocol is the default in Rust 1.70, so we can just leave it
to defaults across all our CI-tested versions.
> Revert "Use cargo's sparse protocol"

- rayon-core/src/latch.rs
- rayon-core/src/scope/mod.rs
The `increment` and `set` methods now have `#[inline]` hints, and the
`counter` fields in `CountLatch` and `CountLockLatch` are now listed
first to increase the chance that layout puts them at the same offset.
(That layout is not critical to ensure, but works out nicely.)
> Improve inlining of scope latch counters

- rayon-core/src/broadcast/mod.rs
- rayon-core/src/latch.rs
- rayon-core/src/registry.rs
- rayon-core/src/scope/mod.rs
The former `enum ScopeLatch` forced a `match` during both `increment`
and `set` (decrement), even though both variants only need to update an
`AtomicUsize` most of the time. #1057 helped hide that for `increment`,
but `set` branching still showed up in perf profiles.
Now this is refactored to a unified `CountLatch` that has a direct field
for its `counter` used in the frequent case, and then an internal enum
for the one-time notification variants. Therefore, most of its updates
will have no `match` reached at all.
The only other use of the former `CountLatch` was the one-shot
termination latch in `WorkerThread`, so that's now renamed to
`OnceLatch`.
> Refactor scope latches to reduce matching

- src/iter/extend.rs
- src/iter/from_par_iter.rs
These all have sequential equivalents in the standard library.
* `impl<T> FromParallelIterator<T> for Box<[T]>`
* `impl<T> FromParallelIterator<T> for Rc<[T]>`
* `impl<T> FromParallelIterator<T> for Arc<[T]>`
* `impl FromParallelIterator<Box<str>> for String`
* `impl ParallelExtend<Box<str>> for String`
> Add more `FromParallelIterator` and `ParallelExtend`

- src/iter/product.rs
- src/iter/sum.rs
Minor update to `sum` and `product` parallel iterators, to have them use arrays instead of chains of iter::once.
> `add` and `mul` now use a `[T, T]` array instead of chained iter::once

- ci/compat-Cargo.lock
- rayon-core/Cargo.toml
- rayon-core/src/lib.rs
From rust 1.59 we have a call for available_parallelism() in the std library and we can remove the dependency on num_cpu.
Open questions for maintainers:
- what is the minimum version of rust that you want to support
- what is the best default value when the call to get parallelism fails? I chose "1".
> Use std:: thread:: available_parallelism() instead of num_cpus dependency

- rayon-core/src/sleep/counters.rs
- src/lib.rs
- Fix `clippy::incorrect_clone_impl_on_copy_type` (denied)
- Fix `clippy::unnecessary_cast` (warning)
> Clippy fixes

- rayon-core/Cargo.toml
- rayon-core/src/lib.rs
- rayon-core/src/registry.rs
- rayon-core/tests/use_current_thread.rs
This generalizes the approach used by targets that don't support threading like
wasm, allowing the builder thread to be part of a new thread-pool.
This PR:
* Builds on top of the PoC implementation from that issue.
* Renames the API as per the comments there.
* Adds a way to clean up the WorkerThread storage once the pool is dropped.
* Documents and tests the APIs.
Feedback welcome. `clean_up_use_current_thread` is not a great name, but I
think it's descriptive, and maybe good enough given it's a rather niche API for
non-global pools?
> core: Introduce ThreadPoolBuilder::use_current_thread.

- rayon-core/src/registry.rs
This was originally done for #1063, in order to reuse this to allow cleaning up the TLS data allocated by use_current_thread.
We ended up not using that, but this refactoring seems useful on its own, perhaps.
> core: registry: Factor out "wait till out of work" part of the main loop.

- rayon-core/src/thread_pool/mod.rs
Add documentation to `rayon::ThreadPool::install()` warning about implicit yield behavior, as discussed in #1105.
> Document implicit yield in install() per #1105

- .github/workflows/ci.yaml
- Cargo.toml
- ci/compat-Cargo.lock
- rayon-core/Cargo.toml
- rayon-core/src/latch.rs
- rayon-core/src/lib.rs
- rayon-core/src/registry.rs
- rayon-core/src/sleep/mod.rs
- src/iter/par_bridge.rs
- src/result.rs
One of the most common complaints I've been receiving in [wasm-bindgen-rayon](https://github.com/RReverser/wasm-bindgen-rayon) that prevents people from using Rayon on the Web is the complexity of manually splitting up the code that uses Rayon into a Web Worker from code that drives the UI.
It requires custom message passing for proxying between two threads (Workers), which, admittedly, feels particularly silly when using a tool that is meant to simplify working with threads for you.
This all stems from a [Wasm limitation](https://github.com/WebAssembly/threads/issues/177) that disallows `atomic.wait` on the main browser thread. In theory, it's a reasonable limitation, since blocking main thread on the web is more problematic than on other platforms as it blocks web app's UI from being …
> Use wasm-sync to allow usage on the main browser thread

- Cargo.toml
- RELEASES.md
- ci/compat-Cargo.lock
- rayon-core/Cargo.toml
- The new `"web_spin_lock"` crate feature makes mutexes spin on the main
browser thread in WebAssembly, rather than suffer an error about forbidden
`atomics.wait` if they were to block in that context. Thanks @RReverser!
> Release rayon 1.8.1 and rayon-core 1.12.1

- README.md
- Update wasm-bindgen-rayon URL to the new repo location (the repo was "soft-moved" / the old one was archived).
- Explain that without the adapter code will also compile but will only use one thread. (fixes #1047)
> Update Wasm section of README

- src/str.rs
- tests/clones.rs
- tests/debug.rs
- tests/str.rs
This matches the standard library's `str::split_ascii_whitespace`, stable since rust-lang/rust#58047.
> Add `ParallelString::par_split_ascii_whitespace`

- src/iter/find_first_last/mod.rs
- src/iter/par_bridge.rs
These are functionally equivalent, but `fetch_update` makes our code simpler.
Also, in the case of `find_first`/`last`, it's now optimized that we don't need a compare-exchange at all when the best position is already equal. That may happen in `find_last` when a result was already found in the current split, or in either method when the split resolution was exhausted.
> Use `fetch_update` instead of `compare_exchange_weak`

- src/iter/test.rs
- src/slice/mod.rs
- src/split_producer.rs
- src/str.rs
- tests/clones.rs
- tests/debug.rs
- tests/str.rs
The standard library versions were stabilized in rust-lang/rust#77858.
- Add `ParallelString::par_split_inclusive`
- Add `ParallelSlice::par_split_inclusive`
- Add `ParallelSliceMut::par_split_inclusive_mut`
> Add inclusive splits on strings and slices

- src/iter/collect/mod.rs
- src/iter/extend.rs
- src/iter/mod.rs
I wasn't exactly sure where the `collect_vec_list` implementation should go, since the necessary internals are in `extend` but it's logically a `collect` function. Also, I feel like the documentation could be better, I'd appreciate feedback on that.
Resolves #1127
> Add ParallelIterator::collect_vec_list

- src/iter/extend.rs
- src/iter/from_par_iter.rs
- src/iter/mod.rs
- src/iter/test.rs
- All `ParallelExtend` impls now try to use the `Vec` pseudo-specialization.
- Add `ParallelExtend` and `FromParallelIterator` for `OsString` to match `std` (since 1.52).
> Extend the ParallelExtend implementations

- rayon-demo/src/find/mod.rs
- src/compile_fail/must_use.rs
- src/iter/blocks.rs
- src/iter/mod.rs
- src/iter/test.rs
- tests/clones.rs
- tests/debug.rs
hi,
here is the code for blocks. in draft request like we discussed last time.
> added by_blocks method

- src/slice/chunk_by.rs
- src/slice/group_by.rs
- src/slice/mod.rs
- src/slice/test.rs
- tests/clones.rs
- tests/debug.rs
Hello, I found this method useful in my code and thought it could be used here. However it relies on #![feature(slice_group_by)] unstable feature of the rust std library and you would probably want to wait for that method to be stabilized anyways so as to stay consistent with whatever naming they choose. This pull request is here for when that happens. Also if any one has any comments on the code I'd really appreciate hearing them.
> Added A `par_chunk_by` method

- FAQ.md
Previously this example in the FAQ as written would've introduced a race condition.
While I know the objective of this example is not to show exactly correct code, it seemed a bit odd to me since there's a whole section earlier about preventing race conditions. The last change was a while ago, so the API wasn't the same, but it would be good to update it so there's no race conditions.
> Change FAQ example with race conditions

- src/range.rs
This avoids potential ambiguity in case the standard library ever
expands `ExactSizeIterator` to more ranges.
Closes #1159.
> Rename `UnindexedRangeLen::len` to `unindexed_len`

- rayon-demo/src/nbody/visualize.rs
Description: This PR resolves a deprecation warning introduced in #1191 related to the use of `winit::event_loop::EventLoop::run`. The deprecated `EventLoop::run` method is replaced with `EventLoop::run_app` as recommended by the `winit` crate.
Changes:
Updated `EventLoop::run` to `EventLoop::run_app` in `rayon-demo/src/nbody/visualize.rs`.
Testing:
Verified that the application compiles without warnings.
Tested the `EventLoop` functionality to confirm no changes in behavior.
Notes:
This resolves the deprecation warning while ensuring compatibility with the latest `winit` API.
> Replace deprecated `EventLoop::run` with `EventLoop::run_app`

- rayon-core/README.md
This pull request contains changes to improve clarity, correctness and structure.
Description correction:
Corrected `APIs are mirror in` to `APIs are mirrored in`
Please review the changes and let me know if any additional changes are needed.
> fix: typos in documentation files

- rayon-core/src/sleep/README.md
I reviewed the entire repository, no more typos found in docs. 
Hope this helps streamline the project!
Best regards,
Bilogweb3
> chore: correct typos docs

- README.md
The gitter.im room (now in Matrix) is rarely used, and the few conversations that come up there would probably be better served by using a GitHub issue or discussion, where they would also be more accessible to future readers.
> Remove the gitter link

- rayon-core/src/registry.rs
This makes it so the **only** mutable access to the `static mut` is a single `ptr::write` initialization, and all shared references are ordered after that by the `Once` guard.
AFAIK we didn't have any actual bug here, but the lint highlighted the danger, and now we have more careful `SAFETY` comments.
> Fix `static_mut_refs` on the global registry

- rayon-core/src/lib.rs
- rayon-core/src/scope/mod.rs
- rayon-core/src/thread_pool/mod.rs
Now that Rust 1.89 is cross-compiling doctests, we need to fix a few things for WebAssembly.
- Ignore `ThreadPoolBuilder` doctests on WebAssembly
- Let `in_place_scope` deal with a global pool using the current thread
> Fix doctests for WebAssembly

- README.md
- RELEASES.md
- rayon-core/README.md
- rayon-core/src/broadcast/mod.rs
- rayon-core/src/latch.rs
- rayon-core/src/lib.rs
- rayon-core/src/registry.rs
- rayon-core/src/scope/mod.rs
- rayon-core/src/sleep/README.md
- rayon-core/src/spawn/mod.rs
- rayon-core/src/spawn/test.rs
- rayon-core/src/thread_pool/mod.rs
- rayon-core/src/thread_pool/test.rs
Compound nouns should generally be spaced, and adjectives hyphenated.
> Improve grammar for compound words

- src/iter/from_par_iter.rs
- src/slice/mod.rs
- src/vec.rs
- `impl<T> IntoParallelIterator for Box<[T]>` and its refs
- `impl FromParallelIterator<_> for Box<str>` via `String`
Closes #1073
> Add boxed impls like Rust 1.80
