- README.md
The example becomes silly for real if it never increments anything. :-)
> Fix broken example in Readme.md

- src/api.rs
- src/job.rs
- src/latch.rs
- src/log.rs
- src/thread_pool.rs
cc @cuviper -- this is based on your patch. What do you think? Though re-reading the issue comments I see you mentioned you might have been doing something like this, if so, sorry to step on your toes!
(Locally I don't see any real change in performance, but I've not done extensive testing, just run the quicksort demo.)
Fixes #9.
> Differentiate between spin and lock latches

- src/par_iter/map.rs
When reading this code I had trouble understanding what `PhantomMap` was for. Hopefully this makes it clearer. I also made it private, and added some missing trailing commas.
> Rename PhantomData wrapper and add comment for clarity

- demo/nbody/Cargo.toml
- demo/nbody/src/main.rs
- demo/nbody/src/nbody.rs
- demo/nbody/src/visualize.rs
This can serve as a benchmark. It also includes a (pretty crude) visualizer currently based on SDL. It should maybe be ported to use OpenGL or something fancier. The visualizer should also report FPS and be switchable between par and seq and a few other things :)
cc #35
> Add an nbody demo

- demo/nbody/Cargo.toml
- demo/nbody/src/main.rs
- demo/nbody/src/nbody.rs
- demo/nbody/src/visualize.rs
Uses `cgmath` for maths, `glium` for graphics, and `docopt` for arg parsing.
Fixes #40.
> Nbody demo improvements

- src/api.rs
- src/test.rs
I would like to fix #39, so I followed the example in TRPL chapter 5.7.
> fix for #39 implement Error and Display for InitError

- .travis.yml
- Cargo.toml
- neg-tests-run/iter_panic.rs
- neg-tests-run/simple_panic.rs
- src/api.rs
- src/job.rs
- src/latch.rs
- src/lib.rs
- src/log.rs
- src/test.rs
- src/thread_pool.rs
> Propagate panics across joins instead of hanging

- .travis.yml
- Cargo.toml
- RELEASES.md
- src/par_iter/slice.rs
- src/par_iter/slice_mut.rs
- src/par_iter/test.rs
Some minor changes to docs etc
> Add a few odds and ends

- README.md
- benches/factorial.rs
- benches/pythagoras.rs
- demo/nbody/src/nbody.rs
- neg-tests-compile/cannot_collect_filtermap_data.rs
- neg-tests-compile/cannot_zip_filtered_data.rs
- neg-tests-run/iter_panic.rs
- src/lib.rs
- src/par_iter/mod.rs
- src/prelude.rs
> Introduce prelude

- src/par_iter/map.rs
- src/par_iter/mod.rs
- src/par_iter/test.rs
These work like `Iterator::cloned()` and `Iterator::inspect()`.
> Add simple `cloned()` and `inspect()` combinators

- src/par_iter/flat_map.rs
- src/par_iter/mod.rs
- src/par_iter/test.rs
- Let flat_map accept any IntoParallelIterator
- Delegate empty FlatMapFolder::complete to its base
> Tweaks for flat_map

- src/par_iter/internal.rs
> Add Sized bounds to meet new WF requirements

- .travis.yml
- Cargo.toml
- demo/nbody/Cargo.toml
- demo/nbody/src/main.rs
- demo/nbody/src/nbody.rs
- demo/nbody/src/visualize.rs
- neg-tests-compile/cell_par_iter.rs
- neg-tests-compile/quicksort_race1.rs
- neg-tests-compile/quicksort_race3.rs
- neg-tests-compile/rc_par_iter.rs
- neg-tests-compile/rc_upvar.rs
Everything that's supposed to error still does, but some of the exact
messages are a little different now.
> update compiletest_rs and sync matched errors

- src/par_iter/mod.rs
- src/par_iter/option.rs
- src/par_iter/test.rs
> IntoParallelIterator for Option and Result

- src/par_iter/collections.rs
- src/par_iter/mod.rs
- src/par_iter/test.rs
> Add vectorized iterators for std::collections

- src/thread_pool.rs
The first commit has the most impact, I think, moving the deque `Worker` into the `WorkerThread` instead of the shared `Registry`. This lets us drop the `unsafe impl Send`/`Sync`.
The rest are more general cleanups.  Each `WorkerThread` can keep its own vector of the other `Stealer`s, and they don't actually need to access the `Registry` at all.
> Clean up deque access

- src/par_iter/vec.rs
The `consumed` flag really only served to let `with_producer` avoid
unsafe code itself.  But that made an implicit safe-unsafe contract with
the drop handler, which isn't good encapsulation.
Now all of the `VecIter` unsafety is contained in `with_producer`, and
it no longer needs a `Drop` implementation at all.
> Refactor VecIter unsafety so it doesn't need Drop

- README.md
> Remove scary mention to #10

- src/thread_pool.rs
I had originally more improvements to `steal_work` based on [Servo's workqueue](https://github.com/servo/servo/blob/master/components/style/workqueue.rs), but they were pretty specialized and after the `scope` change those paths no longer appear in the profile as much as far as I know. I still want to profile it more, but wanted to get this reviewed.
The way to get a `Registry` from a `ThreadPool` is completely nasty, but otherwise I needed to expose it, which is undesirable. Any better solution is appreciated.
> Use a weaker rng and reduce lock contention when possible.

- src/par_iter/mod.rs
- src/par_iter/test.rs
> add a count combinator

- src/api.rs
- src/scope/mod.rs
- src/scope/test.rs
- src/thread_pool.rs
The old scoped code was a bit too eager to pop work off the deque, resulting in linear stack growth in some scenarios -- precisely the thing that `scope` is designed to avoid!
> avoid linear stack growth using scoped APIs

- src/par_iter/mod.rs
- src/par_iter/reduce.rs
Starting simple :)  Looking at https://github.com/nikomatsakis/rayon/issues/149
> Rename mul to product

- src/par_iter/collect/consumer.rs
- src/par_iter/collect/mod.rs
There's a lot less fuss required about invariants in `CollectConsumer`
and `CollectFolder` if we just use `&mut [T]` for the target memory.
We can use standard `split_at_mut` and `into_iter`, instead of dealing
with our own pointer math and hoping we got mutable aliasing right.
> Use slices to simplify vector collect

- src/par_iter/README.md
The README explained why there was no `UnindexedProducer`, but now there
is one, since it was useful for `Range<u64>` and string's `par_chars`.
So, this adds a few words about it, and how it compares to `Producer`.
> Document a little about UnindexedProducer

- src/api.rs
> join function documentation

- src/par_iter/chain.rs
- src/par_iter/enumerate.rs
- src/par_iter/filter.rs
- src/par_iter/filter_map.rs
- src/par_iter/flat_map.rs
- src/par_iter/fold.rs
- src/par_iter/from_par_iter.rs
- src/par_iter/skip.rs
- src/par_iter/take.rs
closes: #246 #245 #243 #242 #241 #240 #239 #238 #237
> Add simple docs to various iterators with links.

- src/iter/collect/test.rs
> add test that drives the collect-consumer, producing too less values

- examples/cpu_monitor.rs
- src/iter/collect/consumer.rs
- src/iter/collect/mod.rs
- src/iter/enumerate.rs
- src/iter/filter.rs
- src/iter/filter_map.rs
- src/iter/find.rs
- src/iter/find_first_last/mod.rs
- src/iter/flat_map.rs
- src/iter/fold.rs
- src/iter/for_each.rs
- src/iter/from_par_iter.rs
- src/iter/internal.rs
- src/iter/len.rs
- src/iter/map.rs
- src/iter/mod.rs
- src/iter/noop.rs
- src/iter/reduce.rs
- src/iter/rev.rs
- src/iter/skip.rs
- src/iter/splitter.rs
- src/iter/take.rs
- src/iter/test.rs
- src/iter/weight.rs
- src/str.rs
- src/vec.rs
It seems like we have a few features of rustfmt that havn't stayed fully current. 
This was current on nightly if that is what you are looking for.
> Rustfmt Reapply

- Cargo.toml
- rayon-core/Cargo.toml
- rayon-core/src/lib.rs
- rayon-core/src/scope/test.rs
- rayon-core/src/test.rs
- rayon-demo/Cargo.toml
- rayon-demo/src/main.rs
- rayon-demo/src/sieve/mod.rs
- rayon-demo/src/tsp/parser.rs
- src/lib.rs
This updates all dependencies to their latest, pruning those unused.
> Update dependencies in all crates

- Cargo.toml
- rayon-core/Cargo.toml
@cuviper has been co-maintainer for some time, but I forgot to update `Cargo.toml`. Thanks @cuviper for being great.
> add Josh Stone as an author

- rayon-core/src/thread_pool/test.rs
We want to test a `spawn` error, but macOS and Windows were somehow
running with the `usize::MAX` stack.  (Probably overflow due to rounding
the page size up or something, and then who knows.)  With `isize::MAX`
we get the error we want, with a little care for 32-bit platforms.
> Make `Builder::spawn` fail more consistently

- rayon-core/src/lib.rs
And use it in `Configuration::new` to save some boilerplate.
> Derive default for `Configuration`

- rayon-core/src/lib.rs
It's in the title.
(thanks for the awesome lib! :smile: )
> Minor doc typo fix

- src/iter/mod.rs
Removed reduce_with_identity, mul, find, and position.
Fixes #305
> Remove Deprecated Interfaces

- rayon-core/src/lib.rs
> Duplicate part of the {Start,Exit}Handler doc to Configuration::{start,exit}_handler

- rayon-core/LICENSE-APACHE
- rayon-core/LICENSE-MIT
> add LICENSE files to rayon-core

- src/iter/flat_map.rs
I found this small while working on #387.
> Fix doc error in flat_map

- src/iter/flatten.rs
- src/iter/mod.rs
- src/iter/test.rs
- tests/compile-fail/must_use.rs
> Add flatten iterator

- rayon-core/src/scope/mod.rs
I see that a pull request for #233 was not accepted. So, added the details for the issue as required.
> document the `Scope` struct

- Cargo.toml
- rayon-demo/src/tsp/mod.rs
- src/lib.rs
> Fix example and add missing attribute to crate

- rayon-core/src/lib.rs
> Add `build` method to `Configuration`.

- Cargo.toml
- examples/cpu_monitor.rs
- rayon-demo/Cargo.toml
- rayon-demo/src/life/mod.rs
- rayon-demo/src/main.rs
- rayon-demo/src/matmul/mod.rs
- rayon-demo/src/mergesort/mod.rs
- rayon-demo/src/nbody/mod.rs
- rayon-demo/src/quicksort/mod.rs
- rayon-demo/src/sieve/mod.rs
- rayon-demo/src/tsp/mod.rs
- docopt -> 0.8
- rustc-serialize -> serde
- glium -> 0.18
> cargo update

- src/result.rs
We don't need a blocking `lock()`, as anybody else holding the lock will
also be writing `Some(error)`, and then the current error is irrelevant.
> Relax the error locking in collecting results

- rayon-demo/src/tsp/graph.rs
> demo/tsp: impl Iterator needs a lifetime annotation

- src/iter/enumerate.rs
- src/iter/skip.rs
- src/iter/take.rs
So, I updated the links to the proper positions.
> `take` is a function on IndexedParallelIterator

- src/delegate.rs
- src/iter/chain.rs
- src/iter/cloned.rs
- src/iter/collect/mod.rs
- src/iter/empty.rs
- src/iter/enumerate.rs
- src/iter/inspect.rs
- src/iter/interleave.rs
- src/iter/interleave_shortest.rs
- src/iter/intersperse.rs
- src/iter/len.rs
- src/iter/map.rs
- src/iter/map_with.rs
- src/iter/mod.rs
- src/iter/once.rs
- src/iter/plumbing.rs
- src/iter/repeat.rs
- src/iter/rev.rs
- src/iter/skip.rs
- src/iter/take.rs
- src/iter/unzip.rs
- src/iter/update.rs
- src/iter/zip.rs
- src/iter/zip_eq.rs
- src/option.rs
- src/par_either.rs
- src/range.rs
- src/slice/mod.rs
- src/vec.rs
Change signature for IndexedParallelIterator:
fn len(&mut self) -> fn len(&self)
Addresses #491
> Immutable borrow self for len()

- src/iter/cloned.rs
- src/iter/empty.rs
- src/iter/inspect.rs
- src/iter/intersperse.rs
- src/iter/len.rs
- src/iter/map.rs
- src/iter/map_with.rs
- src/iter/update.rs
> Specialize some Producer::fold_with methods

- src/collections/mod.rs
- src/iter/mod.rs
- src/lib.rs
- src/option.rs
- src/range.rs
- src/result.rs
- src/slice/mod.rs
- src/str.rs
- src/vec.rs
A few wording changes - mostly at the top of a few files.
> Documentation tweaks

- src/iter/mod.rs
> Add examples to IndexedParallelIterator

- rayon-core/src/lib.rs
- rayon-core/src/registry.rs
- rayon-core/src/test.rs
- rayon-core/src/thread_pool/mod.rs
- src/lib.rs
Re-export ThreadPoolBuildError from rayon
> Rename ThreadPoolInitError to ThreadPoolBuildError

- rayon-core/src/join/mod.rs
> link to par_sort resolves

- .travis.yml
- src/range.rs
> Force lazy_static 1.0.2 for older CI

- Cargo.toml
- rayon-core/Cargo.toml
- rayon-core/src/join/test.rs
- rayon-core/src/lib.rs
- rayon-core/src/scope/test.rs
- rayon-demo/Cargo.toml
- rayon-demo/src/main.rs
- rayon-demo/src/nbody/visualize.rs
- rayon-demo/src/str_split.rs
- src/iter/test.rs
- src/lib.rs
- src/slice/mergesort.rs
- src/slice/test.rs
- tests/str.rs
- `cgmath 0.17`
- `glium 0.23`
- `rand 0.6`
> Update dev and demo dependencies

- rayon-core/tests/stack_overflow_crash.rs
- src/lib.rs
> Reexport current_thread_index function

- src/iter/extend.rs
Mirrors https://github.com/rust-lang/rust/pull/50234/
> impl ParallelExtend<()> for ()

- Cargo.toml
- build.rs
- ci/compat-Cargo.lock
- src/compile_fail/must_use.rs
- src/compile_fail/no_send_par_iter.rs
- src/iter/mod.rs
- src/iter/step_by.rs
- src/iter/test.rs
- tests/clones.rs
- tests/debug.rs
- tests/producer_split_at.rs
this is a pull request for the #494. It add a step_by iterator for `IndexedParallelIterator` producing a iterator that is also indexed parallel iterator. It is Implemented in pull mode.
> add step by parallel iterator.

- rayon-core/src/lib.rs
Updated the rayon-core doc with basic info and links.
> Added documentation for rayon-core

- Cargo.toml
- ci/compat-Cargo.lock
- rayon-core/Cargo.toml
- rayon-core/src/scope/test.rs
- rayon-demo/Cargo.toml
- rayon-demo/src/nbody/nbody.rs
- rayon-demo/src/nbody/visualize.rs
- rayon-demo/src/sort.rs
- rayon-demo/src/str_split.rs
- src/slice/mergesort.rs
- src/slice/quicksort.rs
- src/slice/test.rs
- tests/sort-panic-safe.rs
- cgmath 0.17 -> 0.18
- glium 0.28 -> 0.29
- num 0.2 -> 0.3
- rand 0.7 -> 0.8
- rand_xorshift 0.2 -> 0.3
> Update test/demo dependencies

- build.rs
- src/array.rs
- src/lib.rs
- src/slice/mod.rs
- src/vec.rs
- tests/clones.rs
- tests/debug.rs
- tests/producer_split_at.rs
This requires Rust 1.51, as tested in the build script.
> impl IntoParallelIterator for arrays

- rayon-core/src/sleep/README.md
- src/iter/plumbing/README.md
Signed-off-by: Ryan Russell <git@ryanrussell.org>
> Improve Docs Readabilty

- Cargo.toml
- ci/compat-Cargo.lock
- rayon-core/src/registry.rs
- rayon-core/src/test.rs
- rayon-core/src/thread_pool/mod.rs
- rayon-core/src/thread_pool/test.rs
- Clean up deprecations
- Remove unused autocfg build-dep
> Minor tidying

- src/vec.rs
- tests/drain_vec.rs
> Fix the Drop implementation in case of an empty range

- rayon-core/src/scope/mod.rs
Miri complained when we tried to reconstruct a panic `Box` from an
`AtomicPtr`, because a later call to `mem::forget` invalidated that
pointer, even though we just meant not to drop it. `ManuallyDrop` is a
way to accomplish that *before* we take the pointer.
```
test scope::test::panic_propagate_nested_scope_spawn - should panic ... error: Undefined Behavior: trying to retag from <547680> for Unique permission at alloc207942[0x0], but that tag does not exist in the borrow stack for this location
--> ~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:1014:9
|
1014 |         Box(unsafe { Unique::new_unchecked(raw) }, alloc)
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|         |
|         trying to retag from <547680> for …
```
> Fix ownership invalidation of saved scope panics

- rayon-core/src/job.rs
- rayon-core/src/join/mod.rs
After #1025, clippy is denying [`fn_address_comparisons`][1], and this
is correct that we can't actually guarantee that the pointer we got from
`as_job_ref` will be the same that we produce in a later `PartialEq`.
It's less worrying that different functions could merge to the same
address, because our `StackJob` will still have different data pointers.
We can keep `Copy + Eq` off of `JobRef` with an opaque `id() -> impl Eq`
instead, so we'll be comparing the exact same captured `fn` pointer.
[1]: https://rust-lang.github.io/rust-clippy/master/index.html#fn_address_comparisons
> Be careful comparing `job_ref.execute_fn`

- rayon-demo/data/tsp/README.md
Nothing special; just added a single note into tsp README
> TSP Readme; add not for dj10 source

- rayon-core/src/registry.rs
If a worker thread has jobs in its own queue, then it's not really
headed for an inactive / sleepy state yet, so we can avoid modifying the
registry-wide sleep state.
> Try local jobs first in `wait_until_cold`

- src/iter/par_bridge.rs
> Promise not to buffer `par_bridge`

- src/iter/test.rs
I fixed some typos that I found with [`typos`](https://github.com/crate-ci/typos).
> Fixed typos

- rayon-core/src/spawn/mod.rs
> doc: be more clear about what the 'spawn' does

- src/str.rs
- tests/str.rs
This matches the addition in rust-lang/rust#86336.
> `impl Pattern for [char; N]` and `&[char; N]`

- .github/workflows/ci.yaml
- .github/workflows/pr.yaml
This is copied from how rust-lang/miri-test-libstd does it.
> ci: Use a single action to collect final status

- src/lib.rs
Nothing major. Just adding a missing full stop that I spotted.
> Fixing docs

- rayon-demo/src/tsp/solver.rs
- src/iter/par_bridge.rs
Discussed as follows:
https://github.com/rayon-rs/rayon/issues/1139
> Potential to modify ordering for split_count and tour_counter

- src/iter/mod.rs
Ref: https://github.com/rust-lang/rust/issues/129031
> Allow `unreachable_patterns` for `Infallible`

- .github/workflows/ci.yaml
- **Test i686 as a target only**
- **The WASI target is now wasm32-wasip1**
> Fix CI for i686 and WASI
